### ISSUE TITLE
Cop idea: Identical equality assertion

### ISSUE THREAD

**Issue by andyw8** [rubocop/rubocop-rspec#1130]
An assertion such as this is probably a typo or a flawed test (since it can never fail):

`expect(foo.bar).to eq(foo.bar)`

**Comment by pirj** [comment]
It can fail in rare cases, e.g. `expect(factorial.next).to eq(factorial.next)` would only succeed once. But it's of an exception and the possibility of a mistake is way higher.

I was about to swear that we've had a similar ticket in our backlog, but couldn't find anything. Thanks for reporting!
