### ISSUE TITLE
double/instance_double argument type

### ISSUE THREAD

**Issue by bquorning** [rubocop/rubocop-rspec#1136]
I'm seeing double/instance_double/class_double/object_double/spy etc. being called with sometimes a string, sometimes a symbol (perhaps because the rspec-mocks documentation explicitly allows both), and of course sometimes a constant referring to a class or module.

I think mixing string and symbol arguments is a bit of a mess, so I would propose making a new cop that enforces either one or the other – with strings being the default enforced style. Why? Because `"MyClass"` looks better than `:MyClass` in those cases where you pass in a module name as a string/symbol.

**Comment by pirj** [comment]
[`instance_double` accepts a class](https://github.com/rspec/rspec-mocks/blob/97c972be57f2c060a4a7fb8a3c5700a5ede693f0/lib/rspec/mocks/example_methods.rb#L38), and so does `class_double`/`instance_spy`. I see no good reasons not to use this. Except to avoid excessive class loading when `instance_double` and the class is referenced from globally-defined shared examples, and those shared examples are eagerly loaded from spec helper.

**Comment by pirj** [comment]
I can also add that changing from a class literal to a string/symbol arguably makes the cop unsafe unless [`verify_doubled_constant_names`](https://github.com/rspec/rspec-mocks/blob/3-11-maintenance/lib/rspec/mocks/configuration.rb#L115) is turned on. It is [off by default in RSpec Mocks 3.11](https://github.com/rspec/rspec-mocks/blob/e4a7ececb851562f5f4ce64762e7976da8fe56f2/lib/rspec/mocks/configuration.rb#L8) and the upcoming [4.0, too](https://github.com/rspec/rspec-mocks/blob/4-0-dev/lib/rspec/mocks/configuration.rb#L8) for the reasons I struggle to remember. Related PR [turning on `verify_partial_doubles` by default](https://github.com/rspec/rspec-mocks/pull/1409).

**Comment by corsonknowles** [comment]
We have a very simple Rubocop rule that autocorrects from string to Class for `instance_double`. It does not affect symbol declarations. Is there interest in us open-sourcing this? I'd be happy to push it up.

**Comment by pirj** [comment]
That will be very kind of you, @corsonknowles ! A pr is welcome.

**Comment by corsonknowles** [comment]
Happy to help! Here's a draft PR:

* https://github.com/rubocop/rubocop-rspec/pull/1957

We've run this on over 50,000 and had it in place for a few years. 

I'm running into a little hiccup with the rake tast for documentation (but the ardocs did successfully generate)

**Comment by corsonknowles** [comment]
Thanks to Luc for reporting this, it looks like we can close this issue due to:

* https://github.com/rubocop/rubocop-rspec/blob/a95f2f0d7e785176cbcfea9e70c7fd2fa3d80dfd/lib/rubocop/cop/rspec/verified_double_reference.rb#L50

Discussion here about how to reconcile the two RSpec cops:
* https://github.com/rubocop/rubocop-rspec/pull/1957#discussion_r1785579392

Thanks to @lucthev for reporting this.

**Comment by pirj** [comment]
Thank you!
