### ISSUE TITLE
Cop idea: check descriptions for accidental spaces

### ISSUE THREAD

**Issue by G-Rath** [rubocop/rubocop-rspec#1144]
I'm actually a bit surprised that not only is this not already a rule, I can't find any mention of anything close to it in any issue or PR - so I could be missing something really big, but in case I'm not here goes nothing...

Over in `eslint-plugin-jest` we have a rule called [`valid-title`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/valid-title.md) which does checks against `it`/`test` and `describe` descriptions (`jest` doesn't have `context`) for things like blank titles (similar to `RSpec/ExampleWithoutDescription`), duplicate titles (similar to `RSpec/RepeatedExampleGroupDescription`), and prefixing titles with the test method name (similar to `RSpec/ExampleWording`)

However, it also checks for accidental spaces in titles, which there doesn't seem to be any cop for!
Specifically, the rule looks for leading and trailing whitespace, and provides an autofix to remove them when found.

I can't think of a situation where you'd want to have this space, and so think this could a good addition for `rubocop-rspec`; maybe `RSpec/ExampleSpacing`, or as an extension to the existing `RSpec/ExampleWording`?

I actually think it would be fair to check for double spaces in titles too, but I think there's slightly higher chance of valid titles having that? (but tbh my go-to example of something like `it 'treats "  " as valid'` would probably be better written as `it 'treats multiple spaces as valid'` anyway).

I'm happy to have a go at implementing this if people think it'd make a good cop :)

**Comment by pirj** [comment]
Do you mean something like?
```ruby
it " has  excessive   spacing  " do
```

This should apply to example group, shared group and example wording, right? I don't think that "docstring" is a commonly-used name for it, but AFAIR it is how RSpec calls it internally [[1](https://github.com/rspec/rspec-core/blob/ea8554afd1a2b63677c6593059fa8f2476181deb/lib/rspec/core/example_group.rb#L114), [2](https://github.com/rspec/rspec-core/blob/ea8554afd1a2b63677c6593059fa8f2476181deb/lib/rspec/core/example_group.rb#L210)]. Maybe `RSpec/ExcessiveDocstringSpacing`? See https://github.com/rubocop/rubocop/issues/7077 for cop naming guidelines and practices.

If you're up for it - sure, a PR is welcome.
