### ISSUE TITLE
Published Documentation Appears to Be Incorrect

### ISSUE THREAD

**Issue by jherdman** [rubocop/rubocop-rspec#1145]
Using https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecexamplelength as an example, a `CountsAsOne` param is indicated as supported. This isn't true in the current release, but rather only on the master branch. As a user of the library I'd expect the documentation at the URL to reflect the current release only.

**Comment by bquorning** [comment]
The site has a dropdown where you can choose to see documentation for v1.44, v2.0, v2.1, v2.2 or master.

I don’t know if we can change what version to show by default.

**Comment by jherdman** [comment]
Ah! I didn't realize that dropdown was there. Very handy.

I think you can change this value (https://github.com/rubocop/rubocop-rspec/blob/master/docs/antora.yml#L3) to match the release version?

**Comment by pirj** [comment]
Sorry for the confusion.

Doc version would be one more thing to remember for our releases and will open opportunities for mismatches.
RuboCop itself publishes docs for `master` as well (https://github.com/rubocop/rubocop/blob/master/docs/antora.yml#L3), I think we'll follow this, at least until there's an option to be always point to the latest released version.

There's not much in the changelong, but still - maybe it's time for a release?

**Comment by jherdman** [comment]
Sounds good. Thank you for your courteous and prompt response.
