### ISSUE TITLE
`RSpec/ImplicitSubject` one statement on multiple lines

### ISSUE THREAD

**Issue by dvandersluis** [rubocop/rubocop-rspec#1153]
```ruby
it do
  is_expected.to do_something
    .with_attributes(:foo, :bar, :baz)
end
```

What do we think about allowing this in `RSpec/ImplicitSubject` with `EnforcedStyle: single_line_only`. It's not technically a single line, but it is a single statement.

**Comment by tejasbubane** [comment]
This cop has `single_statement_only` style too [which was undocumented](https://github.com/rubocop/rubocop-rspec/pull/1155). That seems to be a better choice for this case.

**Comment by dvandersluis** [comment]
Oh great thanks @tejasbubane!
