### ISSUE TITLE
Cop idea: Consider the `let` naming as `subject` an offence

### ISSUE THREAD

**Issue by joromir** [rubocop/rubocop-rspec#1157]
Consider the `let` naming as `subject` an offence:

```ruby
let(:subject) { described_class.new }

describe '#result' do
  it 'returns forty two' do
    expect(subject.result).to eq 42
  end
end
```

**Comment by pirj** [comment]
👍 
Would you like to add a such a cop?
I'd suggest using this node pattern:
```ruby
        def_node_matcher :let_subject, <<-PATTERN
          (send nil? {#Helpers.all} {(sym :subject) (str "subject")} ...)
        PATTERN
```

For the cop, use `on_send`, and:
```ruby
def on_send(node)
  let_subject(node) do |helper|
    add_offense(node)
  end
end
```
It should do the job.

It should also handle the block-pass case:
```ruby
block = -> {}
let(:subject, &block)
```
and also `let!`/`subject(:subject)` and strings (`let('subject')`).

I am not certain if we handle the
```ruby
expect(subject.result)
```
as an offence, if not - that's an idea for yet another cop.
