### ISSUE TITLE
Cop idea: prefer `be_empty`

### ISSUE THREAD

**Issue by boris-petrov** [rubocop/rubocop-rspec#1162]
I had the following code:

```ruby
expect(response.headers.first_value('content-encoding').is_empty).to eq(true)
```

Which could be simplified to:

```ruby
expect(response.headers.first_value('content-encoding')).to be_empty
```

It would be nice for `rubocop-rspec` to notify me of such instances.

**Comment by pirj** [comment]
We have `RSpec/PredicateMatcher`, and it handles this case for **predicate** methods: https://github.com/rubocop/rubocop-rspec/blob/e33f8387d87ce73e1fdc8ad8fce659d4762d51d9/spec/rubocop/cop/rspec/predicate_matcher_spec.rb#L17
`is_empty` is not a predicate method, though, `is_empty?` is.

If it happens that `RSpec/PredicateMatcher` doesn't work with chained calls (`response.headers.first_value('content-encoding').is_empty?`), a pull request is welcome.
