### ISSUE TITLE
RSpec/ScatteredSetup: false positive

### ISSUE THREAD

**Issue by ololobus** [rubocop/rubocop-rspec#1165]
I am using rails 6 + rspec + rswag and have a following repeating pattern in my request specs:

```ruby
  path '/clusters/{id}/delete' do
    post 'Delete cluster' do
      tags 'Cluster'
      operationId 'deleteCluster'
      produces 'application/json'
      parameter name: :id, in: :path, type: :integer

      response '200', 'success' do
        before do
          cleanup_operations(existing_cluster)
        end

        schema '$ref' => '#/components/schemas/OperationResult'
        run_test!
      end

      response '409', 'conflict' do
        schema '$ref' => '#/components/schemas/OperationResult'
        run_test!
      end
    end
```

The idea is that model does not allow concurrent operations, so if there are running ones it will return `409` code. But I also want to test `200` response, so I use a cleanup helper, which forcedly marks all operations as finished. This would be fine, but I have several similar endpoints to test, e.g. `start`, `stop`, etc. And for some responses I need before callback and for some of them I do not, thus I cannot declare `before` on the `describe` level.

However, `RSpec/ScatteredSetup` says:
```ruby
spec/requests/api_controller/clusters_spec.rb:147:9: C: RSpec/ScatteredSetup: Do not define multiple before hooks in the same example group (also defined on lines 182, 215, 377, 444, 485, 546, 604, 635).
        before do ...
        ^^^^^^^^^
spec/requests/api_controller/clusters_spec.rb:182:9: C: RSpec/ScatteredSetup: Do not define multiple before hooks in the same example group (also defined on lines 147, 215, 377, 444, 485, 546, 604, 635).
        before do ...
        ^^^^^^^^^
spec/requests/api_controller/clusters_spec.rb:215:9: C: RSpec/ScatteredSetup: Do not define multiple before hooks in the same example group (also defined on lines 147, 182, 377, 444, 485, 546, 604, 635).
        before do ...
        ^^^^^^^^^
spec/requests/api_controller/clusters_spec.rb:377:9: C: RSpec/ScatteredSetup: Do not define multiple before hooks in the same example group (also defined on lines 147, 182, 215, 444, 485, 546, 604, 635).
        before do ...
```
and so on.

And I cannot obey, because it will ruin my test logic. Am I missing something?

**Comment by pirj** [comment]
Your example only has a single `before`, so it's hard for me to make a picture of the whole structure.

I could suggest configuring example groups to include `response`. See https://github.com/rubocop/rubocop-rspec/blob/e33f8387d87ce73e1fdc8ad8fce659d4762d51d9/config/default.yml#L9 and https://docs.rubocop.org/rubocop-rspec/usage.html#rspec-dsl-configuration for an idea.
Be extra careful with that, though, as the default settings might be overridden [due to a bug](https://github.com/rubocop/rubocop-rspec/issues/1126).

**Comment by ololobus** [comment]
The whole structure is more like:
```ruby
describe 'Cluster' do
  path '/clusters/{id}/start' do
    post 'Start cluster' do
      tags 'Cluster'
      operationId 'startCluster'
      produces 'application/json'
      parameter name: :id, in: :path, type: :integer

      response '200', 'success' do
        before do
          cleanup_operations(existing_cluster)
        end

        schema '$ref' => '#/components/schemas/OperationResult'
        run_test!
      end

      response '409', 'conflict' do
        schema '$ref' => '#/components/schemas/OperationResult'
        run_test!
      end
    end

  path '/clusters/{id}/delete' do
    post 'Delete cluster' do
      tags 'Cluster'
      operationId 'deleteCluster'
      produces 'application/json'
      parameter name: :id, in: :path, type: :integer

      response '200', 'success' do
        before do
          cleanup_operations(existing_cluster)
        end

        schema '$ref' => '#/components/schemas/OperationResult'
        run_test!
      end

      response '409', 'conflict' do
        schema '$ref' => '#/components/schemas/OperationResult'
        run_test!
      end
    end
end
but with even more endpoints.

**Comment by pirj** [comment]
Can you please try configuring the DSL?
I would suggest copy and pasting the existing one, and adding `response` to `ExampleGroups/Regular`.
To test that other cops' config is not broken, add some offence and make sure it's still detected after your change.

**Comment by pirj** [comment]
In general, we could suggest `rspec-swagger` to follow this document https://docs.rubocop.org/rubocop-rspec/third_party_rspec_syntax_extensions.html, but the bug prevents from using this without breaking other cops.

**Comment by ololobus** [comment]
Thanks for the response.

> I could suggest configuring example groups to include response.
> I would suggest copy and pasting the existing one, and adding response to ExampleGroups/Regular.

If I put `response` into the ExampleGroups -> Regular it complains about empty example groups:

```ruby
spec/requests/api_controller/clusters_spec.rb:607:7: C: RSpec/EmptyExampleGroup: Empty example group detected.
      response '200', 'success' do
      ^^^^^^^^^^^^^^^^^^^^^^^^^
spec/requests/api_controller/clusters_spec.rb:638:7: C: RSpec/EmptyExampleGroup: Empty example group detected.
      response '200', 'success' do
```

**Comment by ololobus** [comment]
Gotcha, `response` is not an example group logically, it is example itself, so what I need is something like that:
```yaml
RSpec:
  Language:
    ExampleGroups:
      Regular:
        - path
        - post
        - put
        - get
        - delete
    Examples:
      Regular:
        - response
```

Thanks for pointing me in that direction. I got a bunch of other offences, probably since Rubocop/RSpec started properly analyzing my rspec file, but the initial problem is gone.

**Comment by ololobus** [comment]
@pirj, so if I am right, what I can do to prevent someone else from hitting the same issue in the future?

Create issue / PR in the https://github.com/rswag/rswag asking to add `config/rubocop-rspec.yml` file with:
```yaml
RSpec:
  Language:
    ExampleGroups:
      Regular:
        - path
        - post
        - put
        - get
        - delete
    Examples:
      Regular:
        - response
```

and follow https://docs.rubocop.org/rubocop-rspec/third_party_rspec_syntax_extensions.html#packaging-configuration-for-rubocop-rspec ?

**Comment by pirj** [comment]
`response` is effectively an example group if it allows for `before` in it, and it's an RSpec-provided hook.

https://github.com/palkan/action_policy/pull/138 is more representative, where `success` is an example, but has no body https://github.com/palkan/action_policy/pull/138/files#diff-7a633d5704411354d8906e8b463afd2c72bb4f1f12c7049b0e63e410047db58eR10.

Same here, `run_test!` is the example https://github.com/rswag/rswag/blob/05e22c3bd7fff53d40cd8104678dab73d0b7aff7/rswag-specs/lib/rswag/specs/example_group_helpers.rb#L88
It can be treated as `it_behaves_like` (`Includes/Examples` in the configuration).

> Create issue / PR in the https://github.com/rswag/rswag

Right.
I'd suggest mentioning the before mentioned bug, as this may ruin other cops.

**Comment by pirj** [comment]
@ololobus Any update?

**Comment by ololobus** [comment]
Thanks for your previous comment, now I use:
```yaml
RSpec:
  Language:
    ExampleGroups:
      Regular:
        - path
        - post
        - put
        - get
        - delete
        - response
    Examples:
      Regular:
        - run_test!
```
so far so good. I only receive reasonable warnings.

I have not prepared a PR yet, but I found a closed issue https://github.com/rswag/rswag/issues/138. And it seems that they are not really willing to accept something like that. Although I want to try anyway

**Comment by pirj** [comment]
I went ahead and going to fix the bug I've mentioned earlier in https://github.com/rubocop/rubocop/pull/9952

If `rswag` doesn't accept your patch, I suggest you creating a `rubocop-rspec-swag` gem with just the `config/default.yml` in it, to act as a glue between `rubocop-rspec` cops and `rswag` code.

Do you think there's anything actionable left, or we can close this ticket, @ololobus ?

**Comment by ololobus** [comment]
@pirj, yeah, I think so. Thanks for responses, that helped me a lot. I'm closing this one

**Comment by Krupskis** [comment]
@ololobus did you start anything with the `rubocop-rspec-swag` gem that @pirj suggested?

**Comment by ololobus** [comment]
@Krupskis, not yet

**Comment by Krupskis** [comment]
@ololobus Do you plan to do so? I would like to contribute

**Comment by ololobus** [comment]
Yeah, I'm going to do it, but if you are willing to do it right now, then go ahead, sure 👍

**Comment by Krupskis** [comment]
@ololobus I would like to do it together, as I am a beginner, especially at gems, so having some guidance would be pretty cool.
