### ISSUE TITLE
RSpec/LeadingSubject autocorrect causes infinite loop error

### ISSUE THREAD

**Issue by thisismydesign** [rubocop/rubocop-rspec#1168]
I have the following 2 declarations in a long legacy testfile that both cause this error:

```ruby
  describe 'pending_linkedin_imports' do
    describe(subject { PortfolioLink.pending_linkedin_imports })
   # ...
  end

  # ...

  describe 'AASM' do
    describe(subject { create(:linkedin_portfolio_link, employee: employee) })
    # ...
  end
```

This is quite the bad syntax tbh but somehow it works and fails the autocorrect.

**Comment by pirj** [comment]
`describe(subject {` how does it work?

**Comment by thisismydesign** [comment]
I'm not sure. Currently getting rid of this confusing code, nevertheless, it does work and causes an error with `rubocop-rspec`.

**Comment by pirj** [comment]
This code works roughly as following:
```ruby
  describe 'pending_linkedin_imports' do
    nonsense = subject { PortfolioLink.pending_linkedin_imports } # most probably `nil`
    describe(nonsense) # empty example group
    # ...
  end
```

It's a bad code that we have no intention to introduce checks to account for such weird and nonsensical usage.
Thanks for understanding.

Please, next time include error messages and the backtrace of `rubocop --debug`.
