### ISSUE TITLE
RSpec/FactoryBot/AttributeDefinedStatically wrong autocorrect for here documents

### ISSUE THREAD

**Issue by thisismydesign** [rubocop/rubocop-rspec#1169]
```ruby
FactoryBot.define do
  factory :something do
    text <<~EOF
            Some long
            Multiline text
    EOF
  end
end
```

Gets corrected to

```ruby
FactoryBot.define do
  factory :something do
    text { <<~EOF }
            Some long
            Multiline text
    EOF
  end
end
```

This won't be a syntax issue either because  `}` is now taken as part of the document.

**Comment by pirj** [comment]
Is it an assumption? Can you please post the error?
What version of Ruby are you using?
```
 ruby -cw 1.rb
Syntax OK

$ ruby-parse 1.rb

(block
  (send
    (const nil :FactoryBot) :define)
  (args)
  (block
    (send nil :factory
      (sym :something))
    (args)
    (block
      (send nil :text)
      (args)
      (dstr
        (str "Some long\n")
        (str "Multiline text\n")))))
```

Simple check:
```ruby
# 2.rb
s = 2.times.map { <<~TEXT }
  hello
  world
TEXT
puts s
```
```
$ ruby 2.rb
hello
world
hello
world
```

**Comment by thisismydesign** [comment]
There's no assumption, please check the provided example carefully

There's no error. The correction puts a `}` in the here doc.
`text { <<~EOF }`

```
1.18.3 (using Parser 3.0.2.0, rubocop-ast 1.7.0, running on ruby 2.6.6 x86_64-linux)
  - rubocop-rails 2.11.3
  - rubocop-rspec 2.4.0
```

Ruby 2.6.6

TargetRubyVersion is set to 2.6

**Comment by pirj** [comment]
It's not a mistake, it's Ruby syntax, even though it's weird at times. Not the weirdest to my memory.
```ruby
foo(1, 2, <<~TEXT, 3) { |args| puts args }
  text goes here
TEXT
```
is valid, too.

**Comment by pirj** [comment]
> This won't be a syntax issue either because } is now taken as part of the document.

This statement is false.

**Comment by thisismydesign** [comment]
😮 That is my bad then, thanks for clarifying.

Still, I think it'd be much cleaner and less confusing to autocorrect to
```ruby
FactoryBot.define do
  factory :something do
    text do
      <<~EOF
        Some long
        Multiline text
      EOF
    end
  end
end
```

Changed the title from "wrong" to "confusing" in case you'd keep a feature request open for this.

**Comment by pirj** [comment]
This is something I suggest you to play around with.
https://whitequark.org/blog/2013/04/26/lets-play-with-ruby-code/ is a good start.
Since Ruby's syntax has this concept of "identical syntax", two pieces of code that produce the same AST, the reverse transformation of AST to code can't retain some original touches.
Chances are the "styling" is tunable.
