### ISSUE TITLE
RSpec/ExpectChange false positive when calling a method that returns different results each time it is called

### ISSUE THREAD

**Issue by shepmaster** [rubocop/rubocop-rspec#1174]
Before:

```ruby
it 'demonstrates the problem' do
  expect { false }.to change { changes_each_call.time }
end

def changes_each_call
  sleep(1)
  OpenStruct.new(time: Time.zone.now)
end
```

After:

```ruby
it 'demonstrates the problem' do
  expect { false }.to change(changes_each_call, :time)
end

# changes_each_call unmodified
```

This results in `changes_each_call` only being called once when `change` is called. The previous behavior would construct two objects, one each time the block is evaluated.

This bit me when `changes_each_call` was the result of an ActiveRecord query which needs to be fetched from the database to see the change occur.

**Comment by pirj** [comment]
Fair enough.
```ruby
expect { }.to change { rand.to_s }
```
is probably even more indicative.

I believe there's no way to differentiate between a variable and a method call:
```ruby
def changes
  1
end

constant

change { changes.time }
change { constant.time }
```

parses to:
```
(begin
  (def :changes
    (args)
    (int 1))
  (send nil :constant)
  (block
    (send nil :change)
    (args)
    (send
      (send nil :changes) :time))
  (block
    (send nil :change)
    (args)
    (send
      (send nil :constant) :time)))
```
so `(send nil :changes)` vs `(send nil :constant)`.


> This bit me when changes_each_call was the result of an ActiveRecord query which needs to be fetched from the database to see the change occur.

Indeed. Not the only surprise with `change` I can think of, though [[1](https://github.com/rspec/rspec-expectations/pull/1100), [2](https://github.com/rspec/rspec-rails/issues/1173)].

Would you suggest flipping the default enforced style to `block` for this cop?
To do so, we need some proof that the majority prefers in that way. https://github.com/pirj/real-world-rspec is a good source of well-known repos that use RSpec. Are there adjustments to the default style of `RSpec/ExpectChange` there?
I could only find it in:
```
canvas-lms/.rubocop.yml
gitlabhq/.rubocop_todo.yml
```
and it's `Enabled: false` in both.

**Comment by francois-ferrandis** [comment]
Regardless of the default style for this cop, it should be tagged as `SafeAutoCorrect: false` since it can break things (that just happened to me). :wink:

**Comment by pirj** [comment]
This is hard to argue 🤷‍♂️ 👍 

Would you like to send a PR?

**Comment by francois-ferrandis** [comment]
@pirj Sure! 

I have started to do that and I have a question: should I delete all `expect_correction` statements from `expect_change_spec.rb` ? This feels like destroying other people's work. Is there a way to declare the cop auto-correctable only with the `block` style?

**Comment by pirj** [comment]
> delete all expect_correction statements from expect_change_spec.rb

I can't remember working with `SafeAutoCorrect: false` cops, but I guess they still perform autocorrection. Thus, specs for this autocorrection should stay, too. I suggest looking at [our parent project](https://github.com/rubocop/rubocop/blob/master/config/default.yml)'s such cops for inspiration.


> declare the cop auto-correctable only with the block style?

I agree with your previous statement:

> Regardless of the default style for this cop, it should be tagged as `SafeAutoCorrect: false`

`change { rand.to_s }` and `change(rand, :to_s)` will behave differently, and it doesn't depend on the direction of autocorrection - such correction is unsafe.

**Comment by francois-ferrandis** [comment]
You are right, both directions are unsafe!

I am having trouble finding the right way to declare `SafeAutoCorrect: false`. I tried adding it to `default.yml` but then the rake task gives me 

> default.yml is out of sync

Should I change another file instead?

Thank you for your time! :slightly_smiling_face:

**Comment by pirj** [comment]
> default.yml is out of sync

That's ok, you have to commit it, `rake` makes such a check, too.
