### ISSUE TITLE
Bad autocorrect on `RSpec/EmptyHook`

### ISSUE THREAD

**Issue by backus** [rubocop/rubocop-rspec#1175]
Hi old rubocop-rspec friends, long time no issue 😄 

## Versions

```sh
cat Gemfile.lock | grep rubocop
      rubocop (~> 1.17.0)
      rubocop-performance (~> 1.11.3)
      rubocop-rspec (~> 2.4.0)
    rubocop (1.17.0)
      rubocop-ast (>= 1.7.0, < 2.0)
    rubocop-ast (1.7.0)
    rubocop-performance (1.11.3)
      rubocop (>= 1.7.0, < 2.0)
      rubocop-ast (>= 0.4.0)
    rubocop-rspec (2.4.0)
      rubocop (~> 1.0)
      rubocop-ast (>= 1.1.0)
```

## Sample code reproducing issue

```ruby
# frozen_string_literal: true

RSpec.describe Sample do
  let(:foo) { bar }
  let(:bar) do
    baz
  end

  before do
    # A bunch of stuff I have temporarily commented out
    # foo
    # bar
    # baz
  end

  it 'lol' do
    # ignore this
    expect(foo).to be(1)
  end
end
```

## Autocorrect output

```sh
$ bundle exec rubocop -a sample_spec.rb
Inspecting 1 file
E

Offenses:

sample_spec.rb:7:8: E: Lint/Syntax: unexpected token tIDENTIFIER
(Using Ruby 2.6 parser; configure using TargetRubyVersion parameter, under AllCops)
  end  it 'lol' do
       ^^
sample_spec.rb:9:3: C: [Corrected] RSpec/EmptyHook: Empty hook detected.
  before do
  ^^^^^^
sample_spec.rb:11:1: E: Lint/Syntax: unexpected token kEND
(Using Ruby 2.6 parser; configure using TargetRubyVersion parameter, under AllCops)
end
^^^

1 file inspected, 3 offenses detected, 1 offense corrected
```

## File after autocorrection

```ruby
# frozen_string_literal: true

RSpec.describe Sample do
  let(:foo) { bar }
  let(:bar) do
    baz
  end  it 'lol' do
    # ignore this
    expect(foo).to be(1)
  end
end
```

### Additional notes

Obviously, shouldn't turn source code into a syntax error. 

Separately, I usually run into this issue in my editor where rubocop formats on save. Part of me wonders whether there should be a `AllowComments` option?

**Comment by pirj** [comment]
Welcome back, @backus ! 🙌 

> should be a `AllowComments` option?

Sounds reasonable.
When commenting out the contents of the hook in steps, it would break the flow to comment out the whole hook if there are no statements left in it.

**Comment by pirj** [comment]
Would you like to contribute the `AllowComments` option?
Luckily, I don't have to convince you that making contributions is a breeze :smile:

**Comment by backus** [comment]
@pirj thank you for fixing so quickly! I will think about it. I am pretty time constrained these days for work and I've tried to avoid getting back into doing OSS too on the side because it's a bit too addictive for me... Might do it if I vscode-ruby still keeps driving me nuts 😆
