### ISSUE TITLE
RSpec/EmptyExampleGroup warning when using rswag's run_test!

### ISSUE THREAD

**Issue by Krupskis** [rubocop/rubocop-rspec#1177]
rubocop does not recognize rswag's `run_test!` as a test block and results in an unexpected behavior. If this really is a bug, I would love to explore it and try to fix it.

--------

## Expected behavior

I expect this to give no offenses

## Actual behavior

```
spec/integration/menu_spec.rb:3:1: C: RSpec/EmptyExampleGroup: Empty example group detected.
RSpec.describe MenusController do
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Steps to reproduce the problem

A simple spec like this should suffice.

```
require 'swagger_helper'

RSpec.describe MenusController do
  path '/menus' do
    get 'menus' do
      tags 'Menus'
      produces 'application/json'
      response '200', 'success' do
        run_test! do
        end
      end
    end
  end
end
```

## RuboCop version

```
$ bundle exec rubocop -V
0.93.1 (using Parser 3.0.2.0, rubocop-ast 1.7.0, running on ruby 2.6.3 x86_64-darwin20)
```

**Comment by pirj** [comment]
We've discussed pretty extensively how it would be possible to smoothen the rough edges between Rswag and `rubocop-rspec` in https://github.com/rubocop/rubocop-rspec/issues/1165. To make use of the described technique, you'll need to use RuboCop version that includes [this fix](https://github.com/rubocop/rubocop/pull/9952). And it's not yet included in the latest 1.18.4.

Thanks for reporting. Please don't hesitate to ask further questions. This area is interesting and important to make `rubocop-rspec` compatible with many tools that add custom RSpec DSL.

If you want to kick-off `rswag-rubocop-rspec` to include the default configuration, that would be great, too.

**Comment by Krupskis** [comment]
Hey @pirj, thanks for the reply. Could you expand a bit more about this?
> If you want to kick-off `rswag-rubocop-rspec` to include the default configuration, that would be great, too.

**Comment by pirj** [comment]
@Krupskis sure: https://github.com/rubocop/rubocop-rspec/issues/1165#issuecomment-884773009 https://github.com/rubocop/rubocop-rspec/issues/1165#issuecomment-888664525

**Comment by pirj** [comment]
https://github.com/rubocop/rubocop/releases/tag/v1.19.0 released with the fix to DSL configuration loading.

**Comment by Krupskis** [comment]
> https://github.com/rubocop/rubocop/releases/tag/v1.19.0 released with the fix to DSL configuration loading.

@pirj Thanks for the news! does that fix the RSpec/EmptyExampleGroup when only `response` and `run_test!` are present??

**Comment by pirj** [comment]
> does that fix the `RSpec/EmptyExampleGroup` when only `response` and `run_test!` are present?

Provided you configure its DSL properly https://github.com/rubocop/rubocop-rspec/issues/1165, supposedly yes.
I encourage you to test it out.
