### ISSUE TITLE
RSpec/ExampleWording can create awkward language

### ISSUE THREAD

**Issue by jdufresne** [rubocop/rubocop-rspec#1179]
```
rubocop-rspec (2.4.0)
```

Input:

```rb
# frozen_string_literal: true

RSpec.describe 'Foo' do
  describe '#foo' do
    it 'should only do bar' do
      # ...
    end
  end
end
```

Actual output:

```rb
# frozen_string_literal: true

RSpec.describe 'Foo' do
  describe '#foo' do
    it 'onlies do bar' do
      # ...
    end
  end
end
```

Expected output (or similar)

```rb
# frozen_string_literal: true

RSpec.describe 'Foo' do
  describe '#foo' do
    it 'only does bar' do
      # ...
    end
  end
end
```

On a largish project, my team found several other cases:

- `it 'should always` -> `it 'alwayses` (maybe keep always as-is)
- `it 'should still show` -> `it 'stills show` (maybe "still shows ...")
- Too many more to enumerate them all

It is quite possible that this can't be solved well, but I thought I would raise it as it presents a hurdle to adoption.

**Comment by pirj** [comment]
I think `only` is even [mentioned in code docs](https://github.com/rubocop/rubocop-rspec/blob/fe60c94fc095545ae0e64883dbaed28926ab65bc/lib/rubocop/cop/rspec/example_wording.rb#L13):
>  The autocorrect is experimental - use with care! It can be configured with ... `IgnoredWords` (e.g. "only")

Would you like to improve the default configuration so that those cases are properly handled?

I'd suggest running the cop against https://github.com/pirj/real-world-rspec and checking for correctness of corrections of a large sample.

**Comment by pirj** [comment]
Ping

**Comment by jdufresne** [comment]
Sorry, for the late response. 

I will not have time to address this.

If you'd like to close this that is fine. Otherwise, someone else, please feel free to pick it up.

**Comment by MothOnMars** [comment]
We've run into enough issues with this cop that we'll be marking it as unsafe in our `.rubocop.yml`:
```yaml
RSpec/ExampleWording:
  SafeAutoCorrect: false
```
As "the autocorrect is experimental", it may make sense to disable the autocorrection by default. If that seems reasonable, I'd be happy to put in a PR to make that change.

A couple more real-world examples (which admittedly are poorly written specs):
```diff
-      it 'should not change the number of news items, and update the crawl status' do
+      it 'does not change the number of news items, and update the crawl status' do

-      it 'should populate and index just the news items that are valid' do
+      it 'populates and index just the news items that are valid' do
```
