### ISSUE TITLE
Dead link to Code Climate

### ISSUE THREAD

**Issue by ybiquitous** [rubocop/rubocop-rspec#1180]
Hi, I notice that the following link to Code Climate is dead:

https://github.com/rubocop/rubocop-rspec/blob/3538c8f687d5399ef07b30ed9f26af036d66a260/README.md#L70

https://codeclimate.com/changelog/55a433bbe30ba00852000fac

<img width="878" alt="image" src="https://user-images.githubusercontent.com/473530/128970926-1dab332a-e56c-49f1-811d-b5bc274a2644.png">

Unfortunately, I can't find the real link. 😢

**Comment by pirj** [comment]
I couldn't quickly find anything. https://docs.codeclimate.com/docs/rubocop
