### ISSUE TITLE
RSpec/ExampleWording autocorrect clobbers string

### ISSUE THREAD

**Issue by ccutrer** [rubocop/rubocop-rspec#1189]
given

```my_spec.rb
it 'should do something to it\'s subject' do
end
```

running `rubocop --only RSpec/ExampleWording -a -- my_spec.rb`

changes it to

```my_spec.rb
it 'does something to it's subject' do
end
```

which now causes a syntax error (it lost the escaped single quote).

I would expect it to change it to

```my_spec.rb
it 'does something to it\'s subject' do
end
```

preserving the single quote.

Version info:

```
1.21.0 (using Parser 3.0.2.0, rubocop-ast 1.11.0, running on ruby 2.7.2 x86_64-darwin20)
  - rubocop-rails 2.12.2
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.4.0
```

Ruby:

`ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]`

**Comment by pirj** [comment]
It goes beyond my understanding how things work.

A simple fix would probably be to replace `node.value` [here](https://github.com/rubocop/rubocop-rspec/blob/9c626d38b5f700c623f582971c79e8ecc5478fac/lib/rubocop/cop/rspec/example_wording.rb#L99) with something like `node.loc.expression.source` and strip quotes from it. `node.loc.expression.source` returns `"'should do \\' something'"`, while `node.value`/`node.str_content` is `"should do ' something"`.

Ended up with `node.value.include?("'") ? node.loc.expression.source[1..-2] : node.value`.
This fixes your case and the spec is still green. However, if you'll go with this fix, I strongly suggest to check the modified cop against https://github.com/pirj/real-world-rspec

Just a side note that this specific style is not recommended https://rubystyle.guide/#consistent-string-literals-single-quote

**Comment by ccutrer** [comment]
Agreed about the style being bad. To work around the syntax error I changed it to double quotes, so no escaping is needed. This in a massive codebase with many many engineers working on it for many many years. I'm transitioning to Rubocop being enforced, and can't do all cops at once. Fighting the battle of consistent string literals will be one of the last things I apply.

**Comment by pirj** [comment]
> codebase with many many engineers working on it for many many years. Rubocop being enforced

Familiar situation.

I would suggest to start with resolving the issue with strings first, and moving to `rubocop-rspec` after.
However, unfortunately enough, `Style/StringLiteral` doesn't handle this. Filed a ticket https://github.com/rubocop/rubocop/issues/10120

I'm actually on the fence if we should really handle the case you've reported. What do you think?

**Comment by ccutrer** [comment]
I think it's unlikely politically to get `Style/StringLiteral` enforced in my codebase (in either direction). I would still call it a bug that any cop, in isolation, especially one marked as Safe, can modify the code in such a way as to cause syntax errors. I could definitely see it argued that the bug lies in core rubocop (possibly a missing helper method), that outputs an invalid string. But either way, I would not call "run this other cop first" as a valid resolution to this bug.

**Comment by dvandersluis** [comment]
> Please keep in mind that most of us are not aware of the -A/--auto-correct-all option, as rubocop --help doesn't display it.

FYI:
<img width="623" alt="Screenshot_2021-09-23__4_41_PM" src="https://user-images.githubusercontent.com/57964/134580813-8b8a0935-92ce-49c0-bd54-387c4475bb0d.png">

It's there, but there is a _lot_ going on in that help screen so I'm not surprised that it's hard to find. I have some plans to reorganize it.

Also, if there is something that can be autocorrected by `-A` and not`-a`, RuboCop will give you a notice about that after running.

**Comment by pirj** [comment]
Quite unlikely that the fix is possible.

**Comment by mpvosseller** [comment]
Just ran into this as well. If it can't be fixed I guess I'd expect that this rubocop would only run with the `-A` option (safe and unsafe) and NOT with the `-a` (safe only) option.

**Comment by pirj** [comment]
The cop can be fixed, and there’s even a suggestion above how exactly. A PR is welcome, @mpvosseller .
