### ISSUE TITLE
Default config does not respect Department Exclude

### ISSUE THREAD

**Issue by dswij** [rubocop/rubocop-rspec#1191]
(not sure if this belongs to `rubocop-rspec` or `rubocop`)

## Description:
`rubocop-rspec` default `Exclude` option does not respect project's `RSpec/` department `Exclude`

e.g. for the cop `RSpec/BeforeAfterAll`, `Exclude` is defined here 

https://github.com/rubocop/rubocop-rspec/blob/b814f81f529adb684171e5ef6380ce49b9207a0d/config/default.yml#L124-L127

When we define a departmental exclude in a new `.rubocop.yml` in a project:

```yaml
RSpec:
  Exclude:
    - foo_spec.rb
```

`foo_spec.rb` will be overriden, and `RSpec/BeforeAfterAll` will be fired on this file.

## Expected:
As a user, I would not want a default cop-specific exclude to override my project's department-wide settings.

---

### Additional notes:

I have made an [example repository](https://github.com/dswij/rubocop-rspec-exclude-example) demonstrating what happened.

[GH Action](https://github.com/dswij/rubocop-rspec-exclude-example/runs/3728940487) failed after excluding the file in `RSpec` department configuration on `.rubocop_department_exclude.yml` but not when excluding it on a specific cop configuration.

Here is the department exclude that is not respected:

https://github.com/dswij/rubocop-rspec-exclude-example/blob/97eb80b3ad271769baf17693657b84c3d3f2ef94/.rubocop_department_exclude.yml

**Comment by pirj** [comment]
@koic @bbatsov @jonas054 Can you please transfer this to `rubocop`?
I don't think there's anything we can do on `rubocop-rspec` side.

**Comment by pirj** [comment]
@dswij Do you mind closing this and opening the same ticket against [RuboCop itself](https://github.com/rubocop/rubocop/issues/new?assignees=&labels=&template=bug_report.md)?

**Comment by pirj** [comment]
Closing as there's nothing we can do on our side.
