### ISSUE TITLE
Cop Idea: Warn when using `sleep`.

### ISSUE THREAD

**Issue by mollerhoj** [rubocop/rubocop-rspec#1202]
Using `sleep` in a spec is usually asking for trouble: It's a patch for some kind of race condition. I'd like to make a cop that warns about the usage of `sleep`

I'll implement this cop if I can get a 👍 from maintainers :-)

**Comment by pirj** [comment]
I'd love to have a cop that would do the same in production code, too 😄 
Can you provide an example of such a spec?

**Comment by pirj** [comment]
Closing as stale
