### ISSUE TITLE
Error while inspecting for RSpec/LeadingSubject

### ISSUE THREAD

**Issue by alexandrz** [rubocop/rubocop-rspec#1220]
I am getting an error while rubocop is inspecting this file:

```
An error occurred while RSpec/LeadingSubject cop was inspecting /app/spec/support/types/validators.rb:2:2
```

```ruby
module Support
  subject do
    test
  end
end
```

Installed gems:

```
 rubocop (1.23.0)
      parallel (~> 1.10)
      parser (>= 3.0.0.0)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml
      rubocop-ast (>= 1.12.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.14.0)
      parser (>= 3.0.1.1)
    rubocop-performance (1.12.0)
      rubocop (>= 1.7.0, < 2.0)
      rubocop-ast (>= 0.4.0)
    rubocop-rails (2.12.4)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.7.0, < 2.0)
    rubocop-rake (0.6.0)
      rubocop (~> 1.0)
    rubocop-rspec (2.6.0)
      rubocop (~> 1.19)
```

**Comment by pirj** [comment]
Thanks for reporting.

Glancing over the cop's code, there are some oddities.

1. `in_spec_block?` actually checks if the `subject { }` node is **not** inside an example. That is quite a pointless check. When removed, no specs fail.
  I suggest removing `in_spec_block?` altogether.

2. A check that `subject { }` is inside an example group is missing. There is a `inside_example_group?` helper, but it doesn't check shared example groups, so if it happens that `subject { }` is below anything else in a shared example group, it would not be detected.
  I propose to:
 - check other usages of `inside_example_group?` (`factory_bot/syntax_methods.rb`, `capybara/feature_methods.rb`), and see if they miss shared example groups
 - fix `inside_example_group?` to detect shared example groups
 - add examples for shared example groups to other cops' specs
 - add a check `return unless inside_example_group?(node)` to `RSpec/LeadingSubject` to fix your case

Would you like to submit a PR?

**Comment by pirj** [comment]
Ping
