### ISSUE TITLE
Example Has Too Many Lines With `aggregate_failures`

### ISSUE THREAD

**Issue by jacoblockard99** [rubocop/rubocop-rspec#1227]
I am trying to use RSpec aggregate_failures to speed up my specs, but `rubocop-rspec` complains that my example now has too many lines because I have 8 expectations. Is this desired behavior?

**Comment by pirj** [comment]
Thanks for reporting.
This is somehow related to https://github.com/rubocop/rubocop-rspec/issues/379
I suggest adding `IgnoreChained` or `MaxChained` option to the cop.
A PR is welcome.

**Comment by pirj** [comment]
Closing as a duplicate. It’s unclear what cop was triggered. If that was the number if lines - just needs to be adjusted.
