### ISSUE TITLE
Isn't the SubjectStub cop particularly ambiguous about the rules for nested subjects?

### ISSUE THREAD

**Issue by oshiro3** [rubocop/rubocop-rspec#1230]
cf: #1228 

The `SubjectStub` cop prohibits stubs even on nested subjects as an inclusion of its rules.
However, the way the warning message is issued and the strictness of the rule are unclear, and it seems to be a source of confusion for users.

For example, the following should be offensive, but are not detected as offensive.

```
describe '#example' do
  subject(:foo) { described_class.new }
  context 'when I shake things up' do
    subject(:bar) { described_class.new }

    before do
      allow(foo).to receive(:wow) # => Is this offensive?
      # allow(bar).to receive(:wow)  #=> If you remove comment out, it becomes offensive.
    end

    it 'tries to trick rubocop-rspec' do
      expect(bar).to eql(foo)
    end
end
```

It is unlikely that such code would be written intentionally, but it could be unintentionally mixed in, and it should be detected by rubocop's checks.

In addition, there are cases where stubbing a subject is not detected as offensive, such as when nesting by an anonymous subject is not detected as offensive.
It is desirable that these intentions or regularities are clearly stated in the description if possible.

**Comment by bquorning** [comment]
I guess the question is whether `foo` is now “the object under test”?

Looking at [the source](https://github.com/rspec/rspec-core/blob/56f9edf78e63ef5971679e31328949fe87a661f7/lib/rspec/core/memoized_helpers.rb#L444-L455) I would say that no: when an “inner subject” is defined (in this case `bar`), then the only thing that made `foo` special (the `alias_method :subject, :foo`) is no longer in scope and `foo` is just a normal memoized helper (as defined by `let` in line 446).

But @pirj you know the inner working of RSpec much better than me. What do you say?

**Comment by pirj** [comment]
I'd love to see some real examples to have a better picture.

Stricter cop (I've made a mistake in the implementation, it does not ignore subjects from unrelated example groups):
```
55577 files inspected, 2077 offenses detected
```

Current version:
```
55577 files inspected, 1686 offenses detected
```

My eyes are bleeding and my brain is burning after quick inspection:
```ruby
allow(subject).to receive(:log_job_done).and_call_original
```

Let me check once again with a fixed cop that respects group nesting.

Speaking of popularity of the cop across `real-world-rspec` apps (though some of them may not use `rubocop-rspec`!):
```
cartodb/.rubocop.yml: disabled
spree/.rubocop.yml: disabled
canvas-lms/.rubocop.yml: disabled
rubocop/.rubocop_todo.yml: three excluded files (todo)
brew/Library/.rubocop_rspec.yml: disabled (todo)
forem/spec/models/article_spec.rb: disabled for one case
```

**Comment by pirj** [comment]
Updated the cop:
```
55577 files inspected, 1738 offenses detected
```

Less than a hundred new offences detected. I'll add more details to the PR.
