### ISSUE TITLE
`RSpec/RepeatedExampleGroupBody` false positive

### ISSUE THREAD

**Issue by ekohl** [rubocop/rubocop-rspec#1231]
We have the following code: https://github.com/voxpupuli/puppet-trusted_ca/blob/428fa7425a69aa61bd7a18201a4b0bc876eddc50/spec/acceptance/certs_spec.rb#L47-L53

Copied here for an easier overview:
```ruby
describe 'trusted_ca' do
  # ... other code ...

  describe command("/usr/bin/curl https://#{fact('hostname')}.example.com:443") do
    its(:exit_status) { is_expected.to eq 0 }
  end

  describe command("cd /root && /usr/bin/java SSLPoke #{fact('hostname')}.example.com 443") do
    its(:exit_status) { is_expected.to eq 0 }
  end
end
```

This is using [serverspec](https://serverspec.org/)'s `command` and verifies the exit code is 0. Somehow this triggers `RSpec/RepeatedExampleGroupBody` but they're clearly different. Is this a bug?

**Comment by pirj** [comment]
Thanks for reporting. Quite an interesting case.

The body, which in RuboCop's terms is the block passed to `describe`, of those two example groups is identical.


I see that using this DSL is common for `beaker-rspec`:
```ruby
describe file('/voxpupuli-acceptance-test') do
    it { is_expected.to be_file }
```

RSpec's [example group methods arguments](https://github.com/rspec/rspec-core/blob/56f9edf78e63ef5971679e31328949fe87a661f7/lib/rspec/core/example_group.rb#L211) doc suggests it should be a string:
```ruby
      #   @overload $1(doc_string, *metadata, &example_implementation)
      #     @param doc_string [String] The group's doc string.
```

However, [it doesn't have to](https://github.com/rspec/rspec-core/issues/1610#issuecomment-46236668).

`beaker-rspec`'s DSL relies on the fact that [the implicit `subject`](https://relishapp.com/rspec/rspec-core/v/3-9/docs/subject/implicitly-defined-subject) **is** that [docstring unless docstring is a class](https://github.com/rspec/rspec-core/blob/56f9edf78e63ef5971679e31328949fe87a661f7/lib/rspec/core/memoized_helpers.rb#L60).

This DSL, even if quite widespread in Puppet ecosystem, is not something RuboCop RSpec can flawlessly work with.



Random rant:
```ruby
require 'spec_helper'

describe package('httpd'), :if => os[:family] == 'redhat' do
  it { should be_installed }
end
```
This code (https://serverspec.org/), even though it looks readable, is slightly outdated in terms of RSpec:
 - `should` is deprecated and will be removed in a major RSpec version
 - `describe` without receiver is a (default) option, but it will be removed in favour of `RSpec.describe`
 - `:if`/`:unless` will be removed
 - doc_string abuse

A more canonical RSpec way to write such a spec would be:
```
specify { expect(package('httpd')).to be_installed } if os[:family] == 'redhat'
```

**Comment by ekohl** [comment]
> A more canonical RSpec way to write such a spec would be:

That's interesting. I think that does look more readable since it's closer to regular Ruby, rather than really a DSL.

That said, I do wonder about this case where you want to test multiple properties. For example:
```ruby
describe service('httpd') do
  it { is_expected.to be_running }
  it { is_expected.to be_enabled }
end
```

You would end up with a bunch of duplication. It is quite verbose.

**Comment by pirj** [comment]
How would you like:

```ruby
specify do
  expect(service('httpd'))
    .to be_running
    .and be_enabled
end
```

Additionally, it's just one example instead of two. And if there's something heavy setup going on, it will only perform it once, and will make two checks against it.

**Comment by ekohl** [comment]
This issue has quickly become way more enlightening than I expected. I greatly appreciate it.

> How would you like:

That looks very nice. I was not aware that this was possible.

So back to the original problem: how would I rewrite the commands listed in my initial message. They're using [rspec-its](https://github.com/rspec/rspec-its) but looking at the [matcher documentation](https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/have-attributes-matcher) I suppose `have_attributes` would be the correct matcher.

I've opened https://github.com/voxpupuli/puppet-trusted_ca/pull/44 to try out this new syntax in a rather trivial module.

**Comment by pirj** [comment]
With `have_attributes`, you'll still have the same body in those examples:
```ruby
  describe command("/usr/bin/curl https://#{fact('hostname')}.example.com:443") do
    it { is_expected.to have_attrubutes(exit_status: 0) }
  end

  describe command("cd /root && /usr/bin/java SSLPoke #{fact('hostname')}.example.com 443") do
    it { is_expected.to have_attrubutes(exit_status: 0) }
  end
```

The problem is in the first argument to `describe` that sets the `subject` that is later used by `is_expected` (which is a shorthand for `expect(subject)`).

I'd suggest:
```ruby
specify do
  expect(command("/usr/bin/curl https://#{fact('hostname')}.example.com:443"))
    .to have_attrubutes(exit_status: 0)
end
```

or:

```ruby
def execute_without_errors
  have_attrubutes(exit_status: 0)
end

specify do
  expect(command("/usr/bin/curl https://#{fact('hostname')}.example.com:443"))
    .to execute_without_errors
end
```

**Comment by ekohl** [comment]
> I'd suggest:

This is indeed what I thought. I already took the `specify { ... }` change in mind.

The only thing I now run into is that it runs the `specify` blocks before applying the Puppet manifest. I've often struggled to understand rspec ordering. Would using `order: :defined` as suggested on https://relishapp.com/rspec/rspec-core/docs/configuration/overriding-global-ordering help here?

**Comment by ekohl** [comment]
> Where is the manifest applied exactly?

I wrote a shared example in a gem so that we don't need to maintain it in our 100+ modules:
https://github.com/voxpupuli/voxpupuli-acceptance/blob/2107b0f62067a73b6b3f409f073f5c025cc59c9d/lib/voxpupuli/acceptance/examples.rb#L1-L11

> ```ruby
>     let(:manifest) { <<-EOS }
>       class { 'trusted_ca': }
>       trusted_ca::ca { 'test': source => '/etc/ssl-secure/test.crt' }
>     EOS
> ```

Does this syntax work? That would be new to me, but it looks cleaner than what's currently used.

> ```ruby
>     before { apply_manifest(manifest, catch_failures: true) }
> ```

What if this fails? Even applying it the first time can be considered a test. On the other hand, you are right in that it really is also a precondition to all other tests.

I really appreciate the in depth responses. If we ever do meet, I owe you a drink or 2!

**Comment by pirj** [comment]
> Does this syntax work?

Yes. A less mind-blowing option is:
```ruby
let(:manifest) do
  <<-EOS
    class { 'trusted_ca': }
    trusted_ca::ca { 'test': source => '/etc/ssl-secure/test.crt' }
  EOS
end
```

**Comment by pirj** [comment]
> I wrote a shared example

```
  it 'applies with no errors' do
    apply_manifest_on(host, manifest, catch_failures: true)
  end

  it 'applies a second time without changes' do
    apply_manifest_on(host, manifest, catch_changes: true)
  end
```

Does the order matter here? I see that options are different.


I'm wondering why, and how those examples have shared state.
Typically, all examples should run from the clean slate. Shared state is not recommended unless strictly necessary.
https://rspec.rubystyle.guide/#avoid-hooks-with-context-scope

https://relishapp.com/rspec/rspec-rails/v/5-0/docs/transactions

**Comment by pirj** [comment]
```
        before { apply_manifest(manifest, catch_failures: true) }
```

> What if this fails? Even applying it the first time can be considered a test.

Hooks are considered to be a part of the example. If a hook fails - the example fails, too.

> I really appreciate the in depth responses. If we ever do meet, I owe you a drink or 2!

You're welcome! Happy to help streamline specs for the whole Vox Populi.

**Comment by pirj** [comment]
> The first application is allowed to have changes, but no failures. On the second time it may not have changes (otherwise it would not be idempotent).

Those two examples should be wrapped in an example group with `order: :defined`. Otherwise, they may be run in a reverse order.

**Comment by pirj** [comment]
Do you think there is anything actionable for `rubocop-rspec`?

The discussion is more RSpec-related, I suggest us to move to [RSpec's mailing list](https://rspec.info/help/).

**Comment by ekohl** [comment]
I think for now there is nothing actionable here. It's been very enlightening and I'll have to see about changing the style we use in our tests. Thanks for the insights!

**Comment by pirj** [comment]
You're very welcome.

**Comment by ekohl** [comment]
Closing the loop: https://github.com/voxpupuli/puppet-redis/pull/438 is the first place I tried out these lessons. I'm not sure I like the negating style. You have to be quite verbose to combine things. Otherwise it certainly looks better.

**Comment by pirj** [comment]
Glad I could help. Do you mind if I comment there on the PR?
I'm quite concerned regarding the `expect(service(redis_name)).not_to be_enabled.and be_running` syntax. I was believing RSpec [raises an exception in this case](https://github.com/rspec/rspec-expectations/blob/4fa4cd9fdf8cf4493840ad8b90d90ce72744f199/lib/rspec/matchers/built_in/compound.rb#L17). How does it work?

**Comment by ekohl** [comment]
Oh please do comment, I welcome your insight. I was also not entirely sure about that line myself. It does appear to work because when it failed (I used `to` instead of `not_to`) it did properly report.
