### ISSUE TITLE
All rspec cops run on `test` folder also

### ISSUE THREAD

**Issue by bbugh** [rubocop/rubocop-rspec#1235]
For legacy reasons, we have a `test` and a `spec` folder. Test was minitest and is no longer used except for some legacy code tests.

rubocop-rspec runs on the files in the `test` folder, but shouldn't be. Seems like it ought to check for a `spec_helper.rb` or something to verify that the folder is actually an rspec one before parsing.

**Comment by bbugh** [comment]
I was able to resolve this with 

```yml
RSpec/Rails:
  Exclude:
    - test/**/*.rb
```

though it seems like this would be the default.

**Comment by pirj** [comment]
The [default is to include](https://github.com/rubocop/rubocop-rspec/blob/master/config/default.yml#L6):
```
    - "**/*_spec.rb"
    - "**/spec/**/*"
```

Do the files in your `test/` match any of those?

Do you want to research this?

**Comment by bbugh** [comment]
That is odd. No, all of the files under test are either suffix-less or `_test.rb`.

I've tested some more and it seems to only be `RSpec/Rails/AvoidSetupHook` that is running on the test folder. I tested with others, but got confused that there's a `Rails/HttpStatus` and an `RSpec/Rails/HttpStatus`. 

Without any configuration in .rubocop.yml except to include `rubocop-rspec`, no `rubocop-rails`, and given a file `test/rspec_rubocop_test.rb` that should have a bunch of errors:

```ruby
describe MyClass do
  before { allow_any_instance_of(MyClass).to receive(:foo) }

  setup do
    3.times { create :user }
    FactoryBot.build(:whatever)
    head 200
  end

  context 'no when here' do
    it 'fails rubocop' do
      allow(foo).to receive(:bar) { |&block| block.call(1) }
    end
  end
end
```

When running `rubocop test`, the only failure is:

```
test/rspec_rubocop_test.rb:4:3: C: [Correctable] RSpec/Rails/AvoidSetupHook: Use before instead of setup.
  setup do ...
  ^^^^^^^^
```

**Comment by pirj** [comment]
That's strange, but we've seen all kinds off oddities with sub-departments (e.g. `RSpec/Rails`).
So, apparently, [this `Include`](https://github.com/rubocop/rubocop-rspec/blob/766bc1b30a17ade4d36cee8dd310c71e66d5e8a9/config/default.yml#L854) doesn't work as expected.
Would you like to dive into `rubocop` code to determine why this `Include` misbehaves?
Here are some hints: https://github.com/rubocop/rubocop-rspec/pull/1163, https://github.com/rubocop/rubocop/blob/8ae9e0f2081d512faf6e4872980fcd538f9c7fac/lib/rubocop/config.rb#L149

**Comment by pirj** [comment]
Note for the future researchers. Even though [`its` accepts arbitrary arguments](https://github.com/rspec/rspec-its/blob/aca1c95014578cfc43b27dc0ff259909e4c4cd87/lib/rspec/its.rb#L123), the "docstring" of the generated example [is explicitly set to `nil`](https://github.com/rspec/rspec-its/blob/aca1c95014578cfc43b27dc0ff259909e4c4cd87/lib/rspec/its.rb#L171), so all of those arguments can be treated as metadata.

**Comment by pirj** [comment]
I've added a fresh repo following how you describe it, https://github.com/pirj/rubocop-rspec-test-dir.
Results of `bundle exec rubocop`:
```
Offenses:

Gemfile:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
source 'https://rubygems.org'
^
spec/rubocop_spec.rb:1:1: C: RSpec/FilePath: Spec path should end with my_class*_spec.rb.
describe MyClass do
^^^^^^^^^^^^^^^^
spec/rubocop_spec.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
describe MyClass do
^
spec/rubocop_spec.rb:2:12: C: RSpec/AnyInstance: Avoid stubbing using allow_any_instance_of.
  before { allow_any_instance_of(MyClass).to receive(:foo) }
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/rubocop_spec.rb:2:34: C: [Correctable] RSpec/DescribedClass: Use described_class instead of MyClass.
  before { allow_any_instance_of(MyClass).to receive(:foo) }
                                 ^^^^^^^
spec/rubocop_spec.rb:5:5: C: [Correctable] RSpec/FactoryBot/CreateList: Prefer create_list.
    3.times { create :user }
    ^^^^^^^
spec/rubocop_spec.rb:10:11: C: RSpec/ContextWording: Start context description with 'when', 'with', or 'without'.
  context 'no when here' do
          ^^^^^^^^^^^^^^
spec/rubocop_spec.rb:12:35: C: [Correctable] RSpec/Yield: Use .and_yield.
      allow(foo).to receive(:bar) { |&block| block.call(1) }
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
test/rspec_rubocop_test.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
describe MyClass do
^

3 files inspected, 9 offenses detected, 6 offenses auto-correctable
```

For me, the only offence in `test/rspec_rubocop_test.rb` is from `Style/FrozenStringLiteralComment`.

Can you please try on your side?

I suggest checking if you have some `.rubocop*.yml` files in parent directories - RuboCop [may load them as well in certain cases](https://docs.rubocop.org/rubocop/1.29/configuration.html#config-file-locations).

Please don't hesitate to re-open. However, it appears to me that it's a configuration issue, and there's nothing to be fixed in `rubocop-rspec` or `rubocop`. Thanks for understanding.
