### ISSUE TITLE
RSpec/EmptyExampleGroup - false positive when expectations in case statement.

### ISSUE THREAD

**Issue by traylenator** [rubocop/rubocop-rspec#1244]
```ruby
require 'spec_helper'

describe 'base' do
  context 'with onreboot true' do                              
    case facts[:os]['release']['major']
    when '6', '7'
      it { is_expected.to contain_cron('cvmfs_fsck_on_reboot') }
    else
      it { is_expected.not_to contain_cron('cvmfs_fsck_on_reboot') }
      it { is_expected.to contain_systemd__timer('cvmfs-fsck.timer').with_timer_content(%r{^OnBootSec=5min$}) 
    end
  end
end
```

results in 

```
alse_spec.rb:6:3: C: RSpec/EmptyExampleGroup: Empty example group detected. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/EmptyExampleGroup)                     
  context 'with onreboot true' do # rbocop:disable RSpec/EmptyExampleGroup
```
for me this seems a false positive since there is always and expectation in that context. Adding another expectation
outside the case statement then `RSpec/EmptyExampleGroup` does not trip.

Full version of spec file is here - https://github.com/voxpupuli/puppet-cvmfs/blob/master/spec/classes/fsck_spec.rb#L38

Versions:

* rubocop (1.22.3)
* rubocop-ast (1.16.0)
* rubocop-i18n (3.0.0)
* rubocop-rake (0.6.0)
* rubocop-rspec (2.9.0)
* ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]

**Comment by traylenator** [comment]
Can be separated into 

```ruby
describe 'base' do
  context 'with onreboot true', if: ['6','7].include?(facts['os']['release']['major]) do                              
     it { is_expected.to contain_cron('cvmfs_fsck_on_reboot') }
   else
   
   context 'with onreboot true', if: not ['6','7].include?(facts['os']['release']['major]) do                              
     it { is_expected.not_to contain_cron('cvmfs_fsck_on_reboot') }
     it { is_expected.to contain_systemd__timer('cvmfs-fsck.timer').with_timer_content(%r{^OnBootSec=5min$}) 
    end
  end
end
```
but that's a little fragile.

**Comment by pirj** [comment]
Thanks for reporting.
The fix is as easy as teaching [`conditionals_with_examples?`](https://github.com/rubocop/rubocop-rspec/blob/e940c9e14070993fa6efebab13ae8accd5626307/lib/rubocop/cop/rspec/empty_example_group.rb#L158) to also recognize `case`.
Would you like to submit a PR?
