### ISSUE TITLE
Cop idea: use more specific matchers in Capybara

### ISSUE THREAD

**Issue by boris-petrov** [rubocop/rubocop-rspec#1248]
It would be nice to have a cop that warns for usages like:

```rb
expect(page).to have_css('button', exact_text: 'a')
expect(page).to have_css('button[disabled]', exact_text: 'b')
expect(page).to have_css('button:not([disabled])', exact_text: 'c')

expect(page).to have_css('a', exact_text: 'd')
expect(page).to have_css('a.cls', exact_text: 'e')

expect(page).to have_css('table')
expect(page).to have_css('table.cls')
```

And suggest replacement with the following:

```rb
expect(page).to have_button('a')
expect(page).to have_button('b', disabled: true)
expect(page).to have_button('c')

expect(page).to have_link('d')
expect(page).to have_link('e', class: 'cls')

expect(page).to have_table
expect(page).to have_table(class: 'cls')
```

Of course, there are many cases that can't be changed like that (for example when generic attributes are checked like `button[data-foo=1]`) but at least "obvious" code could be checked.

**Comment by pirj** [comment]
Would you like to contribute such a cop, @boris-petrov ?

**Comment by boris-petrov** [comment]
@pirj - I doubt I'll have the time to do it any time soon. :(

**Comment by ydah** [comment]
If don't mind, I'll try contribute on this cop.

**Comment by pirj** [comment]
That would be fantastic, @ydah !

**Comment by ydah** [comment]
Sorry for the delay... PR is now open!
