### ISSUE TITLE
`RSpec/RepeatedDescription` shouldn't warn about `pending` specs

### ISSUE THREAD

**Issue by ojab** [rubocop/rubocop-rspec#1258]
Consider the following
```ruby
pending('Feature is not implemented yet') do
    expect(foo).to eq(bar)
end

pending('Feature is not implemented yet') do
    foo
    expect(SomeStub).to have_been_called
end
```

Right now we have `RSpec/RepeatedDescription: Don't repeat descriptions within an example group.` and if examples are moved to the same `pending` block — we would have `RSpec/MultipleExpectations` violation.
Since specs are testing the same code and depend on the same unimplemented feature — the same description looks appropriate and making up different descriptions just to satisfy the cop is not ideal.

IMHO cop shouldn't warn about pending (and maybe skipped) examples.

**Comment by pirj** [comment]
I agree with the cop - the docstring passed to `pending` is supposed to describe what exactly has not been implemented.

`pending` on itself may mean "not implemented" or "doesn't work exactly as supposed/designed".

Additionally, if those examples all relate to the same unimplemented feature, it makes sense to group them:
```ruby
describe 'a new shiny feature' do
  pending 'shines in the sunlight' do
    # ...
  end

  pending do
    is_expected.to glow_in_the_dark
  end
end
```

**Comment by ojab** [comment]
:okay:, makes sense.
