### ISSUE TITLE
Cop idea: Excluding multi-line statements from `RSpec/ExampleLength` inspection

### ISSUE THREAD

**Issue by johnny-miyake** [rubocop/rubocop-rspec#1261]
`RSpec/ExampleLength` detects this code as an offense.

```ruby
it do
  expect(object).to(
    have_received(:some_method).with(
      value1,
      value2,
      value3,
      value4,
      keyword_arg1: value5,
      keyword_arg2: value6
    )
  )
end
```

Modifying the code like the below solves the offense, but I feel this one is less readable than the original one. (Especially when the name of each argument varies a lot.)
```ruby
it do
  expect(object).to(
    have_received(:some_method).with(
      value1, value2, value3, value4,
      keyword_arg1: value5,
      keyword_arg2: value6
    )
  )
end
```

Should we add another option, or is there any way to avoid the offense by some configuration?

In the discussion where `CountAsOne` was introduced, this opinion makes sense to me.
> I thought that maybe what we really want is to limit the number of top-level statements inside an example.
https://github.com/rubocop/rubocop-rspec/issues/1125

**Comment by pirj** [comment]
What about a 100-lines long:
```
expect(object).to have_received(:some_method).with(
  be_present,
  match(include(have_attributes(
   # lengthly list of 30 lines
```
Would such a declarative example still count as short?

**Comment by johnny-miyake** [comment]
Your point is valid. Then it seems better to disable the cop for each test case by case rather than adding another feature to the cop, right? (Offenses like above may be considered a signal of the need for refactoring, though.)

**Comment by pirj** [comment]
I'm open to consider introduction of an option given an example that would not contribute to the example readability while breaking the default line length constraint.
