### ISSUE TITLE
`RSpec/VerifiedDoubleReference` is not safe to auto-correct

### ISSUE THREAD

**Issue by jrmhaig** [rubocop/rubocop-rspec#1262]
It is possible to use `instance_double` with a string that is not a valid class name;

```ruby
instance_double('not a valid class', **arbitrary_attribute_list)
```

and auto-correct is not safe in this case. I believe that it is correct for this cop to have an auto-correct option but it should be marked as unsafe.

**Comment by pirj** [comment]
Depending on the enforced style, the cop autocorrects either a literal class to a literal string, or the other way around.
The cop assumes that valid arguments to `instance_double` are [a literal class, a literal string](https://github.com/rubocop/rubocop-rspec/blob/a1a3351a0c9ebfe9d9e45e28c42fb3f9764fa33c/lib/rubocop/cop/rspec/verified_double_reference.rb#L15), or a variable referencing an object. The cop ignores variables.

Let's check with RSpec's documentation what are acceptable arguments to `instance_double`.
["Using an instance double" suggests](https://relishapp.com/rspec/rspec-mocks/v/3-9/docs/verifying-doubles/using-an-instance-double):
> It takes a class name or object as its first argument

You may argue that the class passed as an argument might not exist, in the cases when TDD is used, or specs are run in complete isolation. It's a valid point according to ["Verifying doubles" doc](https://relishapp.com/rspec/rspec-mocks/v/3-9/docs/verifying-doubles)
> No checking will happen if the underlying object or class is not defined

This can be confirmed by [RSpec's own specs for `instance_double`](https://github.com/rspec/rspec-mocks/blob/1611752449b5beefa1939dd2a20beb0175d46110/spec/rspec/mocks/verifying_doubles/instance_double_with_class_not_loaded_spec.rb#L20).
This, however, disprove the fact that the argument should still be a literal string that would make a valid class name.

Apparently, you are not using `instance_double` as intended to be used, and this, I suppose, is enforced by another cop, `RSpec/VerifiedDoubles`. If you would, the autocorrection would be completely safe.

On a side note, the RSpec core team recommends using literal strings to avoid excessive class loading when running specs selectively.

**Comment by titusfortner** [comment]
@pirj fwiw, this auto-correct broke my legacy tests; no failures with `VerifiedDoubles` either

**Comment by pirj** [comment]
@titusfortner Do you mind sharing an example?

**Comment by titusfortner** [comment]
after running rubocop with auto-correct, this line causes the test to fail:
https://github.com/SeleniumHQ/selenium/blob/selenium-4.1.0/rb/spec/integration/selenium/webdriver/chrome/profile_spec.rb#L42

I get it's not correct usage, but the code was originally added in 2013... :)

**Comment by pirj** [comment]
@titusfortner I guess a simple
```diff
- ext_file = instance_double(file)
+ ext_file = instance_double(File)
```
fixes the failure?

I guess there's a job for yet another cop to enforce string literals passed to verified double to be valid class names.

>  the code was originally added in 2013

Verified doubles were introduced roughly at the same time - no wonder Selenium code from back then doesn't adhere to the "new" true way of using doubles.

By the way, in RSpec 4, `verify_partial_doubles = true` [becomes the default](https://github.com/rspec/rspec-mocks/pull/1409):

> You should only turn off `verify_partial_doubles` (by setting it to false) if you have a really good reason to.

I believe it's something that needs to be fixed in the code that the cop fails to auto-correct, not to mark the cop as unsafe for autocorrection.
