### ISSUE TITLE
Cop to enforce the first describe of a spec is defined as RSpec.describe

### ISSUE THREAD

**Issue by schinery** [rubocop/rubocop-rspec#1272]
I've checked the docs and don't believe this can currently be done, but would it be possible to create a cop that enforced the first `describe` of a spec has been defined as `RSpec.describe`? 

So something like:

```ruby
# Bad
describe SomeClass do
  describe "#does_something" do
    # ...
  end
end

# Good
RSpec.describe SomeClass do
  describe "#does_something" do
    # ...
  end
end
```

**Comment by pirj** [comment]
This is [one of the non-goals](https://docs.rubocop.org/rubocop-rspec/#enforcing-an-explicit-rspec-receiver-for-top-level-methods-disabling-monkey-patching).

The monkey-patching mode, top-level `describe` with no receiver, [will be removed in RSpec 4](https://github.com/rspec/rspec-core/pull/2803). To ease up the process of upgrading, you can use [Transpec](http://yujinakayama.me/transpec/), which will do the conversion for you.

**Comment by schinery** [comment]
Cool, thanks @pirj. 

I also discovered setting config.expose_dsl_globally = false will make any test not using RSpec. to blow which is good enough for now.
