### ISSUE TITLE
False-positive RSpec/RepeatedDescription when using rspec-its

### ISSUE THREAD

**Issue by arg** [rubocop/rubocop-rspec#1273]
Continuing https://github.com/rubocop/rubocop-rspec/issues/879. We're using `rspec-its` and have examples like this:

```ruby
describe Service do
  describe 'returned values' do
    subject { service }

    before { service.call }

    its(:model) { is_expected.not_to be_valid }
    its(:model) { is_expected.not_to be_persisted }
  end
end
```

Rubocop raises this error on each `its(:model)` line: `C: RSpec/RepeatedDescription: Don't repeat descriptions within an example group.`

I believe this is not correct, since RSpec generated different descriptions for every example based on example's body:
```
Service
  returned values
    model
      is expected not to be valid
    model
      is expected not to be persisted
```
So ideally, in case of examples defined with `rspec-its`, example's body should be the source of this uniqueness check, but not the `its(...)` definitions which may look equal.

**Comment by pirj** [comment]
Fair enough, especially given that negated expectations are not trivial to combine into one.

Would you like to submit a PR?
I'd expect:
1. Taking parts from `lib/rubocop/cop/rspec/repeated_example.rb` that adds some unique example attribute (location?) for `its` to effectively ignore duplicate attribute names.
2. Add an example to `spec/rubocop/cop/rspec/repeated_example_spec.rb` to make sure duplicates are detected (passed with no changes required to the cop):
```ruby
  it 'does not flag examples when different its arguments are used' do
    expect_offense(<<-RUBY)
      describe 'doing x' do
        its(:x) { is_expected.to be_present }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Don't repeat examples within an example group.
        its(:x) { is_expected.to be_present }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Don't repeat examples within an example group.
      end
    RUBY
  end
```

**Comment by pirj** [comment]
I withdraw [my proposal of introducing `IgnoreItsWithSameAttribute`](https://github.com/rubocop/rubocop-rspec/issues/879#issuecomment-605687818), as it seems to make sense to make this the default.

**Comment by pirj** [comment]
Note for the future researchers. Even though [`its` accepts arbitrary arguments](https://github.com/rspec/rspec-its/blob/aca1c95014578cfc43b27dc0ff259909e4c4cd87/lib/rspec/its.rb#L123), the "docstring" of the generated example [is explicitly set to `nil`](https://github.com/rspec/rspec-its/blob/aca1c95014578cfc43b27dc0ff259909e4c4cd87/lib/rspec/its.rb#L171), so all of those arguments can be treated as metadata.

**Comment by pirj** [comment]
Would you like to submit a PR fixing this, @arg ?

**Comment by arg** [comment]
I will try to find some time, but can’t say when.

Best regards,
Andrii

**Comment by pirj** [comment]
Ping @arg

**Comment by ydah** [comment]
If you are still busy, I would like to work on this.

**Comment by arg** [comment]
That would be great
