### ISSUE TITLE
ExpectChange in 2.11.0 makes problematic corrections

### ISSUE THREAD

**Issue by atanbt** [rubocop/rubocop-rspec#1276]
```ruby
expect { a.action }.to change { model.reload.attribute }.from(1).to(0) 
```

gets corrected to

```ruby
expect { a.action }.to change(model.reload, :attribute).from(1).to(0)
```

which is not equivalent (because reload is only called once instead of twice) and can cause the spec to fail.

A second issue is `An error occurred while RSpec/ExpectChange cop was inspecting` occurs when you have something like this:

```ruby
expect { described_class.action }.not_to change { model }
```

The issue here appears to be that the `change { model }` block has no method chain and it can't parse it? This actually allowed us to discover a spec that was testing incorrectly so I don't know if there's a legitimate use of the matcher in this way but either way I'm guessing it should at least be parseable.

**Comment by pirj** [comment]
Thanks for reporting so quickly.
The regression was introduced [here](https://github.com/rubocop/rubocop-rspec/pull/1042/files#diff-0efc3d9e7ed8b2171157524b1a69a5a2a054a98c2bdb83a5719eb9944a9e055cR92).

**Comment by bquorning** [comment]
v2.11.1 has been released with a bugfix.
