### ISSUE TITLE
`RSpec/EmptyLineAfterExample` and `rubocop:disable` directive

### ISSUE THREAD

**Issue by johnny-miyake** [rubocop/rubocop-rspec#1282]
It would be nicer if the autocorrect for `RSpec/EmptyLineAfterExample` handles `rubocop:disable` directive properly.

This code,
```ruby
RSpec.describe Foo do
  it 'does this' do
  end
  # rubocop:disable RSpec/Foo
  it 'does that' do
  end
  # rubocop:enable RSpec/Foo
end
```
is corrected like below with the current version of rubocop-rspec (v2.9.0).
```ruby
RSpec.describe Foo do
  it 'does this' do
  end
  # rubocop:disable RSpec/Foo

  it 'does that' do
  end
  # rubocop:enable RSpec/Foo
end
```

The code should be corrected like below.

```ruby
RSpec.describe Foo do
  it 'does this' do
  end

  # rubocop:disable RSpec/Foo
  it 'does that' do
  end
  # rubocop:enable RSpec/Foo
end
```
I think `rubocop:disable` is placed at the head of a code block in most cases. Some other cops like `Layout/EmptyLineAfterGuardClause` in `rubocop` main repository insert an empty line just before the comment line unless the comment is `rubocop:enable` directive, so it sounds more natural to me if `RSpec/EmptyLineAfterExample` also behaves like that.

---

Btw, at first I thought fixing `EmptyLineSeparation` solves this problem, but I found some test cases for `RSpec::EmptyLineAfterFinalLet` (one of the cops which includes `EmptyLineSeparation`) expects a comment line can follow `let`. 

```ruby
  it 'does not register an offense for comment '\
     'followed by an empty line after let' do
    expect_no_offenses(<<-RUBY)
      RSpec.describe User do
        let(:a) { a }
        let(:b) { b }
        # end of setup

        it { expect(a).to eq(b) }
      end
    RUBY
  end
```

**Comment by pirj** [comment]
Thanks for reporting!

> test cases ... expects a comment line can follow let

I believe this comment is there for indication purposes, and can be disregarded.

> it sounds more natural to me if RSpec/EmptyLineAfterExample also behaves like that.

Indeed.

Would you like to further hack on this?

**Comment by johnny-miyake** [comment]
Yeah, I would love to!
