### ISSUE TITLE
Don't offense `MultipleExpectations` for `expect`s inside conditions

### ISSUE THREAD

**Issue by AlexWayfer** [rubocop/rubocop-rspec#1292]
Hello.

It's probably not common or not easy to implement, but I'd like to not receive an offense from `MultipleExpectations` when `expect`s are in `if`-`else`.

```ruby
shared_examples 'something' do |variable:|
  specify do
    if variable
      expect(subject).to all(part_matching)
    else
      expect(subject).not_to include(part_matching)
    end
  end
end
```

**Comment by pirj** [comment]
After some discussion in the PR and here, I'm more inclined to close this.
But there's this code left that can serve well as a standalone cop if forked.
