### ISSUE TITLE
`.RSpec.Language` configuration isn't available in RSpec when using the `:config` metadata

### ISSUE THREAD

**Issue by born4new** [rubocop/rubocop-rspec#1297]
## Context

[This line](https://github.com/rubocop/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/base.rb#L22) assumes that `.RSpec.Language` configuration will always be available. This line is reached when using `expect_no_offenses` or `expect_offense` helpers.

## The problem

When running specs with the `:config` metadata, [as recommended in the upgrade guide](https://docs.rubocop.org/rubocop-rspec/upgrade_to_version_2.html#use-config-rspec-metadata-in-cop-specs), [the `config` hash in the tests](https://github.com/rubocop/rubocop/blob/51ff1d7e29c985732fe129082c98d66c531a2611/lib/rubocop/rspec/shared_contexts.rb#L102) do not contain this data, and it results in the following error:

```shell
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /Users/gitlab/src/rubocop-rspec/lib/rubocop/cop/rspec/base.rb:22:in `on_new_investigation'
     # /Users/gitlab/src/rubocop/lib/rubocop/cop/commissioner.rb:153:in `block (2 levels) in invoke'
     # /Users/gitlab/src/rubocop/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
     # /Users/gitlab/src/rubocop/lib/rubocop/cop/commissioner.rb:153:in `block in invoke'
     # /Users/gitlab/src/rubocop/lib/rubocop/cop/commissioner.rb:153:in `each'
     # /Users/gitlab/src/rubocop/lib/rubocop/cop/commissioner.rb:153:in `invoke'
     # /Users/gitlab/src/rubocop/lib/rubocop/cop/commissioner.rb:84:in `investigate'
     # /Users/gitlab/src/rubocop/lib/rubocop/cop/team.rb:155:in `investigate_partial'
     # /Users/gitlab/src/rubocop/lib/rubocop/cop/team.rb:83:in `investigate'
     # /Users/gitlab/src/rubocop/lib/rubocop/rspec/cop_helper.rb:50:in `_investigate'
     # /Users/gitlab/src/rubocop/lib/rubocop/rspec/cop_helper.rb:21:in `inspect_source'
     # /Users/gitlab/src/rubocop/lib/rubocop/rspec/expect_offense.rb:180:in `expect_no_offenses'
```

## Current workaround

Manually specifying the config via the `other_cops` let variable:

```shell
  let(:other_cops) do
    {
      'RSpec' => {
        'Enabled' => true,
        'StyleGuideBaseURL' => 'https://rspec.rubystyle.guide',
        'Include' => ['**/*_spec.rb', '**/spec/**/*'],
        'Language' => {
          'inherit_mode' => {
            'merge' => %w[Expectations Helpers Hooks HookScopes Runners Subjects]
          },
          'ExampleGroups' => {
            'inherit_mode' => {
              'merge' => %w[Regular Skipped Focused]
            },
            'Regular' => %w[describe context feature example_group],
            'Skipped' => %w[xdescribe xcontext xfeature],
            'Focused' => %w[fdescribe fcontext ffeature]
          },
          'Examples' => {
            'inherit_mode' => {
              'merge' => %w[Regular Skipped Focused Pending]
            },
            'Regular' => %w[it specify example scenario its],
            'Focused' => %w[fit fspecify fexample fscenario focus],
            'Skipped' => %w[xit xspecify xexample xscenario skip],
            'Pending' => ['pending']
          },
          'Expectations' => %w[expect is_expected expect_any_instance_of],
          'Helpers' => ['let', 'let!'],
          'Hooks' => %w[prepend_before before append_before around prepend_after after append_after],
          'HookScopes' => %w[each example context all suite],
          'Includes' => {
            'inherit_mode' => { 'merge' => %w[Examples Context] },
            'Examples' => %w[it_behaves_like it_should_behave_like include_examples],
            'Context' => ['include_context']
          },
          'Runners' => %w[to to_not not_to],
          'SharedGroups' => {
            'inherit_mode' => { 'merge' => %w[Examples Context] },
            'Examples' => %w[shared_examples shared_examples_for],
            'Context' => ['shared_context']
          },
          'Subjects' => ['subject', 'subject!']
        }
      }
    }
  end
```

There's probably a better workaround, but this is the one I used that did the trick.

## The fix

I suppose adding `.RSpec.Language` to the config [when including the `:config` metadata flag](https://github.com/rubocop/rubocop/blob/51ff1d7e29c985732fe129082c98d66c531a2611/lib/rubocop/rspec/shared_contexts.rb#L56) would fix this issue?

**Comment by pirj** [comment]
[This included context](https://github.com/rubocop/rubocop-rspec/blob/a8101aeb8607d9265414502aed16b459a077feef/spec/shared/default_rspec_language_config_context.rb) makes sure that RSpec DSL configuration (`RuboCop::RSpec::Language.config`) is available for cops in specs.

Can you please check if the top-level example group has `:config` metadata?
Can it be that you are missing [this `require`](https://github.com/rubocop/rubocop-rspec/blob/426513dde29e45872c28b8b1f8f392f8b2811e04/spec/spec_helper.rb#L4)?
```ruby
require 'rubocop/rspec/support'
```

It would be very kind of you to send a PR filling this gap in the documentation for writing custom cops using `rubocop-rspec` as a library.

So far, I'm not convinced there is anything actionable that needs to fixed in `rubocop-rspec`'s code, so I'm inclined to close this.
