### ISSUE TITLE
Provide allowlist for VerifiedDoubles check

### ISSUE THREAD

**Issue by lulalala** [rubocop/rubocop-rspec#1299]
Some libraries utilize dynamic method definitions or `Hashie::Mash` to provide its API interface (e.g.`Restforce::SObject` wraps around the hash representing an object from Salesforce).

We often have to provide a double for these, and `VerifiedDoubles` would complain since the methods aren't defined. Disabling those one by one can be tedious. It would be convenient to have an allowlist of classes which can skip checks.

**Comment by pirj** [comment]
See https://relishapp.com/rspec/rspec-mocks/v/3-9/docs/verifying-doubles/dynamic-classes for a trick that allows to use verified doubles with such dynamic classes in RSpec.
```ruby
RSpec.configuration.mock_with(:rspec) do |config|
  config.before_verifying_doubles do |reference|
    reference.target.define_attribute_methods
  end
end
```

I'm not convinced that RuboCop RSpec should make exceptions to this case where a workaround on RSpec side is available.
