### ISSUE TITLE
[RSpec/Capybara/SpecificMatcher] False-positive with `have_table`

### ISSUE THREAD

**Issue by boris-petrov** [rubocop/rubocop-rspec#1310]
```rb
expect(page).to have_css('table tbody.some-class tr:last-child')
```

This results in a `Prefer have_table over have_css.` warning however in this case I have sub-matchers and that can't be replaced with `have_table`.

Otherwise the rule works perfect, great work!

cc @ydah

**Comment by bquorning** [comment]
Fixed [v2.12.1](https://rubygems.org/gems/rubocop-rspec/versions/2.12.1). Thanks for reporting, @boris-petrov 🙏🏼
