### ISSUE TITLE
`RSpec/Rails/HaveHttpStatus` enabled by default in project without Rails

### ISSUE THREAD

**Issue by rickselby** [rubocop/rubocop-rspec#1313]
In 2.12.1, `RSpec/Rails/HaveHttpStatus` has been enabled by default, but we don't use rails. This is raising offences that we cannot fix.

Is there a way to automatically enable these cops only if Rails is detected? We could manually disable `RSpec/Rails/*` cops, but this issue would affect anyone using this gem without rails, so it feels like something that should be addressed in the gem...

**Comment by pirj** [comment]
What you can do is to add the following to your `.rubocop.yml` to your project's root:
```ruby
RSpec/Rails:
  Enabled: false
```

I don't think there's a reliable way for RuboCop RSpec to detect if Rails is part of the project.

We can think of extracting Rails, Capybara and FactoryBot departments into separate gems, but this will take two major releases, which means ~1.5 years if we do the next major release soon.
