### ISSUE TITLE
Option so one-line/hooks/examples/whatever shouldn’t need to have a newline between them.

### ISSUE THREAD

**Issue by ngouy** [rubocop/rubocop-rspec#1314]
## context

This was already discussed here: https://github.com/rubocop/rubocop-rspec/pull/632#issuecomment-415967045

### what we have today:

If I have
```rb
context "given 1, 2, 3" do
  before { do_something } # offense missing new line after hook
  around { do_something_else } # offense missing new line after hook
  after { do_yet_anothing_thing }

  it { should do something }
end
```

And naturally, would be auto-corrected to

```rb
context "given 1, 2, 3" do
  before { do_something }

  around { do_something_else }

  after { do_yet_anothing_thing }

  it { should do something }
end
```

### Proposition:

An option to the EmptyLineAfterHook so we can have multiple one-liner grouped together withouht new lines
This option could probably have other usage on other cops

WIth this new option, the first code block wouldn't trigger any offense

### Unknowns

Some things I don't know how they should behave. For example:

```rb

context "given before no-one-line blocks" do
  before do
    something
  end
  after do
    something_else
  end
end

context "given a mix of before blocks" do
  before { do_something } 
  after do
    something
  end
  around { do_yet_another_thing }
end
```

**Comment by pirj** [comment]
I'm guilty of separating `before` hooks when they do unrelated things, e.g.:
```ruby
before { allow(user).to receive(:delete).and_return(true) }

before { user.tags << 'long-inactive' }
```
but I prefer to keep a line between them.

**Comment by ngouy** [comment]
regardless if we use many `before` (or any other hook) or not, I think it's fair to allow consecutive one-liner for both same and different hooks, in order to have a single one-liner hooks block

both 
```rb
before { do_smt }
before { do_smt_else }

it "..."

# or 

before { do_smt }
after { un_do_smt }

it "..."
```

Seems fair

**Comment by pirj** [comment]
[`RSpec/EmptyLineAfterHook` has a `AllowConsecutiveOneLiners` option](https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecemptylineafterhook), see [example](https://github.com/rubocop/rubocop-rspec/blob/master/spec/rubocop/cop/rspec/empty_line_after_hook_spec.rb#L328):
```ruby
        RSpec.describe User do
          before { do_something }
          before { do_something_else }

          it { does_something }
        end
```

Do you also suggest to allow no empty line between hooks, `let`s and examples when they all are one-liners like below, @ngouy ?

```ruby
RSpec.describe 'foo' do
  subject(:foo) { Foo.new }
  let(:bar) { Bar.new }
  before { do_smt }
  after { do_smt_else }
  it { is_expected.to ... }
end
```

**Comment by ngouy** [comment]
yea @pirj I'm the one that introduced it to solve it 😂 
Just forgot to close this issue

`AllowConsecutiveOneLiners` is the way
