### ISSUE TITLE
Cop idea: `NoExpectations`

### ISSUE THREAD

**Issue by zverok** [rubocop/rubocop-rspec#1319]
When I thought about it, I actually was surprised nobody came with it yet :)
So, basically it wold be cool (I'd do it myself, but don't have enough time atm) to have a cop checking whether an example has no expectations at all. It is actually more frequent problem than one might imagine. Some examples might include:
* lazy "it just works" check (`it { subject }` -- it should be at least `expected.to_not raise_error`)
* homemade matcher-less check, e.g. example code which just `raise Something` to signal fail (or worse `puts "something"`) instead of choosing proper matcher
* just accidental copy-paste or rewrite errors, leaving expectations out of the code, or commenting them
* the one where I came with idea: we had a code looking like this
```ruby
it {
  expect(something).to receive(:method).and_return(value)
  subject 
}
```
rspec-rubocop was unhappy (because you shouldn't mix mock and expectation), and suggested to use `allow`. The code author changed it to `allow`... And everything was green, and it is not immediately obvious that the code tests nothing, "it was just small stylistic check suggested by rubocop".

As there is already `MultipleExpectations` cop, it seems that the opposite check wouldn't be too hard to implement, right?..

**Comment by pirj** [comment]
Hey 👋 

I remember we've stumbled across a problem with copy-pasta'd `it { validates_presence_of(:attribute) }` is spec of a project we were working on.

However, such a cop would be a subject for false positives, at least with the coding style that I practice sporadically:
```ruby
def works
  is_expected.to validate_presence_of(attribute)
end

describe '#status' do
  let(:attribute) { :status }
  it { works }
end
```

There has also been a discussion somewhere in RSpec's issue tracker that it is barely possible to catch such example in runtime. I can dig to find it if you like.

**Comment by Darhazer** [comment]
See also #208

**Comment by pirj** [comment]
Just for the reference, https://github.com/rspec/rspec-core/issues/759
