### ISSUE TITLE
[RSpec/Capybara/SpecificMatcher] False-negative for `click_link`

### ISSUE THREAD

**Issue by boris-petrov** [rubocop/rubocop-rspec#1326]
```rb
find('#some-id a.some-class').click
```

This could be changed to:

```rb
find('#some-id').click_link(class: 'some-class')
# or
find_by_id('some-id').click_link(class: 'some-class')
```

I'm still not sure if that's better but I wanted to put that for discussion here.

cc @ydah, @pirj, @bquorning

**Comment by ydah** [comment]
```ruby
find('#some-id a.some-class').click

find('#some-id').click_link(class: 'some-class')
```

In the above case, it looked good as `RSpec/Capybara/SpecificActions`.
ref: https://rubydoc.info/github/jnicklas/capybara/master/Capybara%2FNode%2FActions:click_link

**Comment by ydah** [comment]
```ruby
# bad
find('#some-id')

# good
find_by_id('some-id')
```

And in the above case, `RSpec/Capybara/SpecificFinders` ?
ref: https://rubydoc.info/github/jnicklas/capybara/Capybara/Node/Finders
