### ISSUE TITLE
[RSpec/Capybara/SpecificMatcher] False-negative for `have_link`

### ISSUE THREAD

**Issue by boris-petrov** [rubocop/rubocop-rspec#1330]
```rb
expect(page).to have_css('a.disabled', text: 'some text')
```

This should warn that it can be converted to:

```rb
expect(page).to have_link('some text', class: 'disabled')
```

cc @ydah, @pirj, @bquorning

**Comment by ydah** [comment]
This problem has been resolved by https://github.com/rubocop/rubocop-rspec/pull/1328 .
Also, there were not enough test cases for this case, so that has been resolved by https://github.com/rubocop/rubocop-rspec/pull/1339 .
