### ISSUE TITLE
Cop Idea: prevent "it works" description

### ISSUE THREAD

**Issue by BigBigDoudou** [rubocop/rubocop-rspec#1337]
I see too many this:

```ruby
it "works" do
  # ...
end
```

Specs are not just here to prevent bugs, but are, as the name implies, specifications. In other words, a documentation we can use as developer to understand what the code is supposed to do.

So it could be nice to enforce a description of "what it does". Preventing "it works" would be a good start 😋 

```ruby
# bad

it "works" do
  # ...
end

# good

it "marks the task as done" do
  # ...
end
```

**Comment by pirj** [comment]
Sounds great. Would you like to open a PR with such a cop? It should be an easy one. There's `RSpec/ContextDescription` for the reference.

**Comment by Darhazer** [comment]
It can have a configuration for disallowed patterns

**Comment by BigBigDoudou** [comment]
> Sounds great. Would you like to open a PR with such a cop? It should be an easy one. There's `RSpec/ContextDescription` for the reference.

That would be my first cop but there's no rush so yeah I can do it someday.

**Comment by akrox58** [comment]
took a stab at this cop requirement! happy to make any changes!
