### ISSUE TITLE
[RSpec/Capybara/SpecificMatcher] False-negative for `have_field`

### ISSUE THREAD

**Issue by boris-petrov** [rubocop/rubocop-rspec#1342]
[has_field](https://www.rubydoc.info/gems/capybara/Capybara/Node/Matchers#has_field%3F-instance_method) handles a bunch of cases which can replace for example:

```rb
expect(page).to have_css('input')
expect(page).to have_css('input[type="checkbox"]')
expect(page).to have_css('textarea')
# etc
```

Same for the negative cases - `expect(page).to have_no_css('input')`.

cc @ydah 

P.S. Also:

```rb
# bad
expect(find('input').value).to eq('foobar')
# good
expect(page).to have_field(with: 'foobar')
```

Or something.

**Comment by ydah** [comment]
Thank you so much!

```ruby
expect(page).to have_css('input')
expect(page).to have_css('input[type="checkbox"]')
expect(page).to have_css('textarea')
# etc
```
This one has created a PR: https://github.com/rubocop/rubocop-rspec/pull/1343 .

```ruby
# bad
expect(find('input').value).to eq('foobar')
# good
expect(page).to have_field(with: 'foobar')
```
This one but I am inclined to put something else cop in charge of this one instead of `SpecificMatcher`.

**Comment by boris-petrov** [comment]
No, thank ***you*** for the hard work on these! Makes writing Capybara much easier!

I agree that the last example is better to go in a different cop.
