### ISSUE TITLE
[RSpec/Capybara/SpecificMatcher] False-positive with pseudo-classes

### ISSUE THREAD

**Issue by boris-petrov** [rubocop/rubocop-rspec#1351]
```rb
expect(page).to have_selector('button:first-of-type:focus')
```

This gives a warning but I don't think it's possible to express this with `have_button`.

cc @ydah

**Comment by ydah** [comment]
I guess we need to consider the cases that cannot be replaced by pseudo-classes.
It may take some time, but I will work on it.

**Comment by ydah** [comment]
Indeed it is. Thank you so much @boris-petrov 
I guess we need to consider the cases that cannot be replaced by pseudo-classes.
It may take some time, but I will work on it.
