### ISSUE TITLE
RSpec/ChangeByZero auto-correct creates syntax errors

### ISSUE THREAD

**Issue by masuyama13** [rubocop/rubocop-rspec#1353]
I'm using `&` matcher, which doesn't work with negative form.
https://github.com/rspec/rspec-expectations/blob/main/lib/rspec/matchers/composable.rb#L25

In this case, auto-correct can be unsafe.

Example:
```rb
expect { subject }.to change { Task.count }.by(0) & change { TaskUser.count }.by(0)
```

running `rubocop -a`

Creates:
```rb
expect { subject }.to change { Task.count } not_to change { TaskUser.count }
```
This is syntactically incorrect.

Versions:
rubocop-rspec: 2.11.1
```
% bundle exec rubocop -v
1.27.0
% bundle exec ruby -v   
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [aarch64-linux]
```

**Comment by ydah** [comment]
That is the issue, but I believe it has been resolved by https://github.com/rubocop/rubocop-rspec/issues/1353 . Please wait for the next release.

**Comment by ydah** [comment]
For test cases, we are creating patches to be added: https://github.com/rubocop/rubocop-rspec/pull/1355
It appears to be working fine, so I think it's fine.

**Comment by ydah** [comment]
@masuyama13 A new version has been released😀 Please check if it works and if it works as expected, please close this Issue.

**Comment by Darhazer** [comment]
I confirm that with `2.13.1` this is either not being corrected, of if `NegatedMatcher: not_change` is configured, corrected to
```
expect { subject }.to not_change(Task, :count) & not_change(TaskUser, :count)
```

**Comment by ydah** [comment]
This is a different Issue from this one, but there seems to be a case where a fix to `Layout/LineLength ` and `Style/BlockDelimiters` causes a SyntaxError.

original
```ruby
    expect { subject }.to change { Task.count }.by(0) & change { TaskUser.count }.by(0)
```

bundle exec rubocop -A --only Layout/LineLength    
```ruby
    expect { subject }.to change { Task.count }.by(0) & change {
 TaskUser.count }.by(0)
```

bundle exec rubocop -A --only Style/BlockDelimiters
```ruby
    expect { subject }.to change { Task.count }.by(0) & change do
 TaskUser.count end.by(0)
```

The following syntax error occurs
```command
     Failure/Error:
          expect { subject }.to change { Task.count }.by(0) & change do
       TaskUser.count end.by(0)
     
     TypeError:
       nil is not a symbol nor a string
```

**Comment by ydah** [comment]
Indeed, I probably shouldn't have brought it up here. Sorry for going off topic.

**Comment by masuyama13** [comment]
@ydah 
I confirmed that it works as expected. Thank you for fixing it.
