### ISSUE TITLE
Feature Request: Support suffix for RSpec/ContextWording

### ISSUE THREAD

**Issue by okuramasafumi** [rubocop/rubocop-rspec#1356]
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspeccontextwording

Currently only `prefix` is supported for `RSpec/ContextWording`, but for some languages, only prefix cannot make description sound natural. I'm a native speaker of Japanese so here I'd like to take Japanese as an example.

```ruby
description '#some_method' do
  # Bad
  '条件1' do
    # When condition 1 is fulfilled
  end

  # Good
  '条件1が満たされるとき' do
    # When condition 1 is fulfilled
  end
end
```

Here, the better context for me is the one that ends with 'とき', meaning `if` or `when` in Japanese.
In general, when rubocop-rspec supports suffix for context wording, it can help writing context in other languages than English. And in some situations, we need to write contexts in our native languages, not English. In addition, `RSpec/ContextWording` doesn't mean that it only supports prefix.
In English, suffix is not important in terms of context. So, the default value for suffix can be empty. With empty default value, we can benefit from restricting suffix while it doesn't effect existing users.

**Comment by ydah** [comment]
It is important to note that in the use case you are proposing, suffixes and prefixes need to behavior differently.
The `RSpec/ContextWording` prefix match checking is strict as follows.

```ruby
# for example - `Prefixes: [when]`
# good
context 'when something' do
end

# bad
context 'whenever something' do
end
```

In Japanese, each word is not separated by a space. Therefore, to check words such as those in the example, the following will work differently for prefix and suffix.

```ruby
# for example - `Suffixes: [if]`
# good
context 'something if' do
end

# good
context 'something serif' do
end
```

> In English, suffix is not important in terms of context. So, the default value for suffix can be empty.

However, as mentioned above, in English, suffixes is not be contextually important, so I think you should be fine.
