### ISSUE TITLE
Cop idea: cop that will enforce `.to eq`

### ISSUE THREAD

**Issue by schinery** [rubocop/rubocop-rspec#1359]
Is there is a cop that can enforce the style of `.to` as sometimes getting mixed examples in our codebase, for example `.to(eq)` and `.to eq`, so wondering if there is anything that can enforce:

```ruby
# Good
expect(element.name).to eq("Country")

# Also good (maybe?)
expect(element.name).to eq "Country"

# Bad
expect(element.name).to(eq("Country"))
``` 

I've been looking through the [RSpec cops](https://docs.rubocop.org/rubocop-rspec/cops_rspec.html) and can't see anything, so suspect not, but wondering if this would be useful?

**Comment by Darhazer** [comment]
Related: #754
Slightly related: #416

**Comment by schinery** [comment]
Ah didn't see #754, thanks @Darhazer will close as definitely the same thing
