### ISSUE TITLE
Missing config/obsoletion.yml

### ISSUE THREAD

**Issue by guillaumewrobel** [rubocop/rubocop-rspec#1382]
Hi there,

it seems that rubocop-rspec-2.13.0 broke things

```ruby
Failure/Error: require_relative "../config/environment"

Errno::ENOENT:
  No such file or directory @ rb_sysopen - /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-rspec-2.13.0/config/obsoletion.yml
```

**Comment by bquorning** [comment]
Fixed in [v2.13.1](https://rubygems.org/gems/rubocop-rspec/versions/2.13.1)

**Comment by ShockwaveNN** [comment]
@bquorning Seems you've forgotten to make GitHub release

https://github.com/rubocop/rubocop-rspec/releases

v2.13.0 is the latest

**Comment by bquorning** [comment]
Fixed

**Comment by ydah** [comment]
Sorry for the inconvenience.
Thank you so much @hosamaly and @guillaumewrobel .

**Comment by guillaumewrobel** [comment]
No, thank **you**.
