### ISSUE TITLE
RSpec/ReturnFromStub yields false positives and makes unsafe autocorrections

### ISSUE THREAD

**Issue by ryanfb** [rubocop/rubocop-rspec#1399]
Example:
```ruby
expect(helper).not_to receive(:facet_display_value_sort) { [] }
```
Triggers:
```
C: [Correctable] RSpec/ReturnFromStub: Use and_return for static values.
```
Which when run with `rubocop -a` (safe autocorrect) produces the code:
```ruby
expect(helper).not_to receive(:facet_display_value_sort).and_return([])
```
Which results in the error:
```
Failure/Error: expect(helper).not_to receive(:facet_display_value_sort).and_return([])
RuntimeError:
   `and_return` is not supported with negative message expectations
```

See also: #947

**Comment by ryanfb** [comment]
Changed title to reflect that this also generates false positives.

**Comment by pirj** [comment]
What does the block that you pass to receive do in this case?
I suspect it's ignored by RSpec for negative expectations, isn't it?
See https://github.com/rspec/rspec-mocks/blob/2c70bfbb5bc0f59525032615c8fa989dd1ade243/lib/rspec/mocks/message_expectation.rb#L74, https://github.com/rspec/rspec-mocks/blob/2c70bfbb5bc0f59525032615c8fa989dd1ade243/lib/rspec/mocks/matchers/receive.rb#L30 for the reference.
Proof:
```ruby
RSpec.describe 'Useless block passed to negated `receive` matcher' do
  it 'ignores the block' do
    foo = double
    expect(foo).not_to receive(:bar) { fail "oh, no, it doesn't" }
  end
end
```

Solution: remove the useless `{ [] }` part from your code.
