### ISSUE TITLE
RSpec/Capybara/SpecificMatcher false positive with count

### ISSUE THREAD

**Issue by jcoyne** [rubocop/rubocop-rspec#1406]
I see this message
```
spec/features/grouped_results_spec.rb:22:23: C: RSpec/Capybara/SpecificMatcher: Prefer have_link over have_css.
      expect(page).to have_css 'a', count: 1
```

however, there is no way to assert a specific number of links appear using `have_link`  See https://github.com/teamcapybara/capybara/blob/f7ab0b5cd5da86185816c2d5c30d58145fe654ed/lib/capybara/node/matchers.rb#L331 

This is with rubocop-rspec-2.13.2

**Comment by ydah** [comment]
I think it can be replaced by `have_link ` as follows.

```
expect(page).to have_link(count: 2)
```

`have_link` is here and accepts keyword arguments as **option.
https://github.com/teamcapybara/capybara/blob/a9fd24012257bba2afa6f36b7c99231c6a069a5e/lib/capybara/rspec/matchers.rb#L80-L84

and the valid options are as follows:
https://github.com/teamcapybara/capybara/blob/a9fd24012257bba2afa6f36b7c99231c6a069a5e/lib/capybara/spec/session/has_link_spec.rb#L43

**Comment by jcoyne** [comment]
Okay, maybe the capybara documentation was just misleading to me
