### ISSUE TITLE
RSpec/Dialect does not seem to be detecting violations

### ISSUE THREAD

**Issue by unikitty37** [rubocop/rubocop-rspec#1409]
Given the following `.rubocop.yml`:

```yaml
AllCops:
  NewCops: disable
RSpec:
  Enabled: true
RSpec/Dialect:
  PreferredMethods:
    xit: skip
```

and the following `spec/test_spec.rb`:

```ruby
# frozen_string_literal: true

require 'rails_helper'

RSpec.describe Test do
  xit 'works' do
    value = 1

    expect(value).to eq(1)
  end
end
```

then `rubocop spec/test.yml` should fail with the message "Prefer 'skip' to 'xit'".

However, RuboCop passes it. The same occurs with the example given in the documentation. I'm not sure if I'm configuring it wrong or if it's broken somehow.

* rubocop (1.36.0)
* rubocop-rails (2.16.1)
* rails (7.0.3.1)
* ruby 3.1.2p20

Incidentally, the documentation for RSpec/Dialect isn't all that clear on what to do if I want to *only* use 'skip' — do I need to specify all the others individually? (And is it possible to require `it '…', skip: true` rather than `skip` in the test body using RSpec/Dialect?)

```
RSpec/Dialect:
  PreferredMethods:
    xit:skip
    xspecify:skip
    xexample:skip
    xscenario:skip
```

**Comment by ydah** [comment]
`RSpec/Dialect` cop is disabled by default. Can you please check if it works as expected by changing .rubocop.yml as follows and enabling it.

```diff
AllCops:
  NewCops: disable
RSpec:
  Enabled: true
RSpec/Dialect:
  PreferredMethods:
    xit: skip
+  Enabled: true
```

**Comment by unikitty37** [comment]
Ah — that would explain it 🤦 Thanks!

It doesn't seem to differentiate between `skip: true` in the `it…` line and an inline `skip` in the test body, so I'll probably need to write a custom cop for that.

**Comment by pirj** [comment]
Don't hesitate to submit it if you like, @unikitty37
