### ISSUE TITLE
Idea: make spec support available in the gem

### ISSUE THREAD

**Issue by tdeo** [rubocop/rubocop-rspec#1418]
Hello,

I was trying to extend rubocop-rspec with a few additional rules to enforce coding practices we have in my team, and I ran into the fact that I cannot include the `spec_helper` and shared contexts from the gem to test my extension.

What rubocop does is that they have their rspec support tools (contexts, expect_offenses and so on) defined in a subdirectory of their [`lib` folder ](https://github.com/rubocop/rubocop/tree/master/lib/rubocop/rspec) so that this tooling is available when you `require 'rubocop'` in your Gemfile.

Would you agree to a similar approach in `rubocop-rspec`? Happy to make a PR if so.

**Comment by bquorning** [comment]
Would this be solved by #1377? The issue seems similar.

**Comment by pirj** [comment]
I've checked briefly the `expect_offenses`, and it appears that [it doesn't do anything useful presently](https://github.com/rubocop/rubocop-rspec/pull/1421), despite expectations.


`spec/shared/autocorrect_behavior.rb` is legacy with `expect_correction`/`expect_no_corrections`.
`spec/shared/detects_style_behavior.rb` seems useful, it's a shame we don't use it in all cops.

So #1377 should do the job.
Can you try it out, @tdeo ?

**Comment by tdeo** [comment]
Hey @pirj,

Not sure when I can give it a try but it looks exactly like what I'll have in mind
