### ISSUE TITLE
`RSpec/SortMetadata` autocorrect broke code for `it_behaves_like`

### ISSUE THREAD

**Issue by ShockwaveNN** [rubocop/rubocop-rspec#1435]
1. Create sample rspec file like this:
```ruby
# frozen_string_literal: true

RSpec.shared_examples 'some example' do |parameter1, parameter2|
  it 'uses the given parameter' do
    p "par1: #{parameter1}"
    p "par2: #{parameter2}"
    expect('a').to eq('a')
  end
end

describe 'enterprise' do
  it_behaves_like 'some example', 'b', 'a' do
    let(:obj) { 'b' }
  end
end

```
2. run it and get output:
```
"par1: b"
"par2: a"
.

Finished in 0.00213 seconds (files took 0.08339 seconds to load)
1 example, 0 failures

```
3. Run autocorrect for this: `rubocop -A spec/test_spec.rb`
Result will be:
```ruby
# frozen_string_literal: true

RSpec.shared_examples 'some example' do |parameter1, parameter2|
  it 'uses the given parameter' do
    p "par1: #{parameter1}"
    p "par2: #{parameter2}"
    expect('a').to eq('a')
  end
end

describe 'enterprise' do
  it_behaves_like 'some example', 'a', 'b' do
    let(:obj) { 'b' }
  end
end

```
5. Run it again:
```
"par1: a"
"par2: b"
.

Finished in 0.00207 seconds (files took 0.08415 seconds to load)
1 example, 0 failures
```

So order of arguments is change and this may broke codebase

Env:
```
1.37.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 3.1.2) [x86_64-linux]
  - rubocop-performance 1.15.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.14.1


```

**Comment by pirj** [comment]
Thanks for reporting!

I believe the fix should be:
```diff
- #rspec? {#Examples.all #ExampleGroups.all #SharedGroups.all #Hooks.all #Includes.all}
+ #rspec? {#Examples.all #ExampleGroups.all #SharedGroups.all #Hooks.all}
```
and a spec making sure we don't mess with positional arguments order of `include_examples`/`include_context`/`it_behaves_like` with and without blocks.

[A short reference of how RSpec deals with metadata](https://github.com/rspec/rspec-core/pull/2878).

Would you like to send a PR, @ShockwaveNN ?

**Comment by ShockwaveNN** [comment]
> Would you like to send a PR, @ShockwaveNN ?

Sorry, I think I'll pass. I'm happy to report issues, but not sure that I've enough free time to dig in the code right now

**Comment by pirj** [comment]
No worries, I'll take care of it.
Meanwhile, stuck with a peculiar bug where the removal of `#Includes.all` is causing RSpec DSL config not to load in specs 🤯
