### ISSUE TITLE
RSpec/Rails/InferredSpecType causes cascading errors for the default structure of request specs

### ISSUE THREAD

**Issue by shepmaster** [rubocop/rubocop-rspec#1436]
To reproduce:

```
rvm use 3.1.2
rails new repro
cd repro
bundle add rspec rspec-rails rubocop rubocop-rspec
rails generate rspec:install
rails generate rspec:scaffold cow
cat > .rubocop.yml <<EOF
require:
  - rubocop-rspec

AllCops:
  NewCops: enable
EOF
rubocop spec/routing -A
rubocop spec/routing
```

The final run of `rubocop` will have this warning:

```
spec/routing/cows_routing_spec.rb:5:1: C: RSpec/FilePath: Spec path should end with cows_controller*_spec.rb.
RSpec.describe CowsController do
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It seems odd that the cop and the generated body of the request spec are at odds with each other.

---

- rspec (3.11.0)
- rspec-rails (6.0.1)
- rubocop (1.37.1)
- rubocop-rspec (2.14.1)

NOTE: cop introduced in #1365

**Comment by shepmaster** [comment]
This _may_ be what y'all expected, and if so, I'd love to hear suggestions about what should be changed — the argument to  `describe` or the file path.

**Comment by pirj** [comment]
I suggest making an exception and keeping `type: :routing` in `RSpec/InferredSpecType`. Just becase RSpec Rails' [controller](https://github.com/rspec/rspec-rails/blob/59a1d9a9f1fa947b00ab3e635455743b1f0956a7/lib/generators/rspec/controller/controller_generator.rb#L47) and [scaffold](https://github.com/rspec/rspec-rails/blob/59a1d9a9f1fa947b00ab3e635455743b1f0956a7/lib/generators/rspec/scaffold/scaffold_generator.rb#L64) have special file naming schema.

@bquorning @Darhazer @ydah @r7kamura Would you agree?

**Comment by ydah** [comment]
I agree with you.
https://relishapp.com/rspec/rspec-rails/v/6-0/docs/routing-specs/named-routes

**Comment by ydah** [comment]
I can work on it right after this, so if no one has started this yet, I will.

**Comment by pirj** [comment]
My apologies, I did, hold on for a PR.

**Comment by ydah** [comment]
I see, that's good to know :) Thank you very much.

**Comment by r7kamura** [comment]
I'm thinking about changing the `RSpec/FilePath` Cop to check if the path is under `spec/routing/`. Would this not work?

**Comment by pirj** [comment]
Sounds reasonable, @r7kamura 👍
