### ISSUE TITLE
Autocorrect FactoryBot/ConsistentParenthesesStyle with omit_parentheses produces syntax error from multi-line instances

### ISSUE THREAD

**Issue by DMA57361** [rubocop/rubocop-rspec#1442]
To match the style generally used throughout our code I've switched the new `RSpec/FactoryBot/ConsistentParenthesesStyle` cop to `EnforcedStyle: omit_parentheses`. We've some cases of FactoryBot.create calls spread across multiple lines (due to many arguments, large values, whatever) and if autocorrect is run the brackets are just removed... producing invalid code.

Given this contrived example file `spec/models/user_spec.rb`:
```
# frozen_string_literal: true

require 'rails_helper'

RSpec.describe User, type: :model do
  let(:user) do
    FactoryBot.create(
      :user,
      name:     'John Smith',
      username: 'jsmith',
      email:    'jsmith@example.org'
    )
  end
  specify { expect(user.username).to eq 'jsmith' }
end

```

Run `rubocop -a spec/models/user_spec.rb`:

```
$ rubocop -a spec/models/user_spec.rb
Inspecting 1 file
E

Offenses:

spec/models/user_spec.rb:7:16: C: [Corrected] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call without parentheses
    FactoryBot.create(
               ^^^^^^
spec/models/user_spec.rb:8:12: E: Lint/Syntax: unexpected token tCOMMA
(Using Ruby 2.7 parser; configure using TargetRubyVersion parameter, under AllCops)
      :user,
           ^
spec/models/user_spec.rb:13:3: C: [Corrected] RSpec/EmptyLineAfterFinalLet: Add an empty line after the last let.
  end
  ^^^

1 file inspected, 3 offenses detected, 2 offenses corrected
```

Presumably the first offense makes a change that causes the Lint/Syntax error?
The end result for the user_spec.rb is this, which is a syntax error:

```
# frozen_string_literal: true

require 'rails_helper'

RSpec.describe User, type: :model do
  let(:user) do
    FactoryBot.create 
      :user,
      name:     'John Smith',
      username: 'jsmith',
      email:    'jsmith@example.org'
    
  end

  specify { expect(user.username).to eq 'jsmith' }
end
```

Ideally multi-line instances need to be ignored even if the configuration is for `EnforcedStyle: omit_parentheses`

## RuboCop version

```
$ rubocop -V
1.37.1 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 2.7.6) [x86_64-darwin18]
  - rubocop-performance 1.15.0
  - rubocop-rails 2.17.1
  - rubocop-rspec 2.14.1
```

**Comment by pirj** [comment]
Thanks for reporting!

> Ideally multi-line instances need to be ignored even if the configuration is for EnforcedStyle: omit_parentheses

Not necessarily:
```ruby
    FactoryBot.create :user,
      name:     'John Smith',
      username: 'jsmith',
      email:    'jsmith@example.org'
```

What do you think, @DMA57361 ?

**Comment by DMA57361** [comment]
A fair point. Frankly, I'm not personally bothered too much by either of these possible outcomes as it's not breaking things, so whatever the path of least resistance is works for me.

I guess the result will end up getting further adjusted by other style cops anyway, eg the above would trigger an offense for the later params not being aligned with the user symbol (at least with our config... I've lost track of what's default or not). So do whatever works and rely on the rest of the style cops to tidy up to the local config? 🤷
