### ISSUE TITLE
Add separate `RSpec/ExampleLength` configuration for `aggregate_failures`

### ISSUE THREAD

**Issue by ojab** [rubocop/rubocop-rspec#1465]
There are times when we need to check order of things happening and something like
```ruby
before { allow(Foo).to receive(:bar) }

specify do
  do_something

  aggregate_failures do
    expect(Foo).to have_received(:bar).with(:x).ordered
    expect(Foo).to have_received(:bar).with(:y).ordered
    expect(Foo).to have_received(:bar).twice
  end
end
```
is already an offense with the default config. Not sure about the number, but it should be >5.

And since `aggregate_failures` could be set in metadata — probably we should exclude `aggregate_failures do; end` from the count to get consistent results.

**Comment by ojab** [comment]
It's simplified example, case in hand is more like
```ruby
expect(Foo).to have_received(:bar).ordered
expect(ErrorHandler).to have_received(:bar).ordered
expect(Foo).to have_received(:baz).ordered
```
so compound expectation wouldn't work, unfortunately (or I can't think of the way to make it work).

IMHO `aggregate_failures` implies that there would be multiple expectations (there is already exception in `RSpec/MultipleExpectations` for that) and `RSpec/ExampleLength` about `don't make setup and expectation overly long to be unreadable`. 
With `aggregate_failures` and multiple single-line expectations it doesn't become unreadable, but allowed per-expectation line count goes way down.

`aggregate_examples` as a metadata would help here, but 
1. Not sure how it will behave if `do_something` raises (e. g. will it still show all the expectation failures?) 
2. `aggregate_failures` as a block is a thing and should be accounted for as a worst case.

**Comment by pirj** [comment]
> how it will behave if `do_something` raises (e. g. will it still show all the expectation failures?)

There's no way this exception would allow the block to continue its execution, so no `expect` would be reached. This goes along with how it would behave if `do_something` is outside `aggregate_failures`, isn't it?
I'm trying to point out that there is no point of using `aggregate_failures do` block in the example body if you can set it via metadata.

**Comment by ydah** [comment]
It seems to duplicate with https://github.com/rubocop/rubocop-rspec/issues/1227

**Comment by ydah** [comment]
I tried to see if I could fix this, but it seems a little difficult.
What we really want to do is to be able to add `aggregate_ failures` to the `CountAsOne` option, but currently it is implemented entirely in the Util classes managed by rubocop/rubocop, so I think I need to override them with rubocop-rspec.

https://github.com/rubocop/rubocop/blob/7b8726132be1148d625a2005f283aa4c761fab92/lib/rubocop/cop/metrics/utils/code_length_calculator.rb#L24-L38

**Comment by pirj** [comment]
It’s in your power to adjust the defaults.

Also, since the First of yhe AAA, Arrange is in the hook, why not put the Act there too and only leave the Assert in the example?

It really depends.
However, i don’t feel like changing how we detect the length of the example by not counting multiple lines inside eg yhe aggregare_failures block
