### ISSUE TITLE
Cop idea: restrict `expect { ... }.not_to raise_error()`

### ISSUE THREAD

**Issue by pirj** [rubocop/rubocop-rspec#1484]
Suggested by @Darhazer [here](https://github.com/rubocop/rubocop-rspec/pull/1456#issuecomment-1315150349).

```ruby
expect { raise 'dffd' }
  .not_to raise_error
```
would fail with
```
  1) is expected not to raise Exception
     Failure/Error: expect { raise 'dffd' }.not_to raise_error

       expected no Exception, got #<RuntimeError: dffd> with backtrace:
```
Without `expect { }`:
```
     Failure/Error: raise 'fddf'

     RuntimeError:
       dffd
```

[`rspec-expectations` would NOT warn](https://github.com/rspec/rspec-expectations/blob/6ebb53150c1b1a629e45a4649fa7965e6a95e39a/lib/rspec/matchers/built_in/raise_error.rb) about such a usage.
But in general, it's at best pointless.

❓ Discussion point: should the cop only be triggered when there's an expectation inside `expect { expect(...).to ... }`, or just the use of `not_to raise_error` in general?

**Comment by Darhazer** [comment]
I was just suggesting that, in scope of the Capybara cops, we may want not to use assertion methods that would raise, and expect not to raise, but instead use the methods that would return value, and expect against that return value

**Comment by pirj** [comment]
My point here was that it's pointless to write
```ruby
expect { something }.not_to raise_error
```
when one can just write
```ruby
something
```
and that would fail with roughly the same output.

However, I agree that some may prefer to be explicit, and that writing
```ruby
it "doesn't fail" do
  something
end
```
is an example with zero expectations.

@ydah Would you agree with the above styling that @Darhazer suggests for capybara cops, would it always apply? May I kindly ask you to file a ticket if so?
