### ISSUE TITLE
RSpec/Capybara/NegationMatcher changes behavior of tests

### ISSUE THREAD

**Issue by pmustel** [rubocop/rubocop-rspec#1488]
I thinks the whole idea with RSpec/CapybaraNegationMatcher is wrong. It should not be there because it will change behavior of the tests.

There is a difference in in writing
case 1:
 ` expect(page).to have_no_link(x)`

case 2:
  `expect(page).not_to have_link(x)`

case1 will wait for a link to disappear. It will take time only when the link exist (fault case).
case2 will wait assert that a link does not appear. It will take time only when the link does not exist (pass case).

Using case 1 for asserting that a link doens't appear gives false positives since it exits (with pass) without waiting for elements to be rendered.

Using  case2 gives much slower executions since it always waits in the 'pass' case.

**Comment by ydah** [comment]
It is our understanding that there is no functional difference between Capybara's RSpec matchers as shown below as well as in the documentation.

>Capybara's RSpec matchers, however, are smart enough to handle either form. The two following statements are functionally equivalent:
>
>expect(page).not_to have_xpath('a')
>expect(page).to have_no_xpath('a')

https://github.com/teamcapybara/capybara/blob/master/README.md#asynchronous-javascript-ajax-and-friends

**Comment by pmustel** [comment]
You have a point. It seems like Capybara has changed. I didn't know that. So new both

case1:
   expect(page).to have_no_link(x)

case 2:
  expect(page).not_to have_link(x)

Works like case 1.

Then to get the second case working as expected I have to write

  found = page.has_link?(x)
  expect(found).to be_falsey

Even more confusing is capybara documents they stress on using the right choice (in your link)

# Given use of a driver where the page is loaded when visit returns
# and that Capybara.predicates_wait is `true`
# consider a page where the `a` tag is removed through AJAX after 1s
visit(some_path)
!page.has_xpath?('a')  # is false
page.has_no_xpath?('a')  # is true


Anyway for Rubocop, I think it whould be better have enforced style: 'have_no' as default for this Cop. Because then it works like expected.

Thank you for giving me this insight and keep up your good work. We have improved our rspec code very much using rubocop-rspec.
________________________________
Från: Yudai Takada ***@***.***>
Skickat: den 17 november 2022 12:57
Till: rubocop/rubocop-rspec ***@***.***>
Kopia: Peter Mustel ***@***.***>; Author ***@***.***>
Ämne: Re: [rubocop/rubocop-rspec] RSpec/Capybara/NegationMatcher changes behavior of tests (Issue #1488)


It is our understanding that there is no functional difference between Capybara's RSpec matchers as shown below as well as in the documentation.

Capybara's RSpec matchers, however, are smart enough to handle either form. The two following statements are functionally equivalent:

expect(page).not_to have_xpath('a')
expect(page).to have_no_xpath('a')

https://github.com/teamcapybara/capybara/blob/master/README.md#asynchronous-javascript-ajax-and-friends

**Comment by pirj** [comment]
@twalpole Would you be so kind to shed some light regarding RSpec matchers?

**Comment by pmustel** [comment]
There is no bug. Just my limited knowledge about capybara matchers.
