### ISSUE TITLE
False positive: PendingWithoutReason and factories

### ISSUE THREAD

**Issue by tagliala** [rubocop/rubocop-rspec#1514]
Hi,

I don't know if this should be taken into consideration, however this newly introduced cop may fire false positives with factories

### versions

```
1.40.0 (using Parser 3.1.3.0, rubocop-ast 1.24.0, running on ruby 3.0.4) [x86_64-darwin22]
  - rubocop-performance 1.15.1
  - rubocop-rails 2.17.3
  - rubocop-rspec 2.16.0
```

### Reproducible test case

```rb
FactoryBot.define do
  factory :task do
    pending
  end
end
```

`pending` is taking into advantage the `traits_for_enum` functionality of FactoryBot, which automatically create traits for existing enums in the model

### Output

```
Offenses:

spec/factories/tasks.rb:3:5: C: RSpec/PendingWithoutReason: Give the reason for pending.
    pending
```

### Workaround

in `rubocop.yml`

```yml
RSpec/PendingWithoutReason:
  Exclude:
    - 'spec/factories/**/*'
```

**Comment by mikdiet** [comment]
I also have false positive, when tested method named `pending`, as in `expect(statement.pending).to eq 0.0`

**Comment by ydah** [comment]
Thank you for the feedback! We are attempting to correct this below.

- https://github.com/rubocop/rubocop-rspec/pull/1515
- https://github.com/rubocop/rubocop-rspec/pull/1516
