### ISSUE TITLE
RSpec/PendingWithoutReason in 2.16.0 gives false positive for every method in the code called `pending`

### ISSUE THREAD

**Issue by jarkko** [rubocop/rubocop-rspec#1521]
Example:

```
spec/models/tax_report_spec.rb:40:14: C: RSpec/PendingWithoutReason: Give the reason for pending.
      expect(r.pending).to be(false)
             ^^^^^^^^^
```

Seems like it shouldn't catch cases where `pending` is called on an object in the test body.

**Comment by ydah** [comment]
Thank you for reporting the feedback!

This issue has been fixed by the following PR. Please wait for the next release.
- https://github.com/rubocop/rubocop-rspec/pull/1515

**Comment by pirj** [comment]
Thanks for reporting. Closing as fixed/being worked on.
