### ISSUE TITLE
Feature request: detect predicate matcher ending with `?`

### ISSUE THREAD

**Issue by okuramasafumi** [rubocop/rubocop-rspec#1535]
This idea comes from my silly mistake. Following code:

```ruby
expect(foo).to has_key?(:bar)
```

where `foo` is a Hash. Do you find a mistake? Yes, in this code RSpec calls `has_key??` method, not `has_key?` method which I expected.
Here comes the fact that in Ruby we can NOT define a method like `has_key??`. So the example above will never pass.

So my Cop idea is that it detects a predicate matcher ending with `?` and (probably unsafely) corrects it with removing ending `?`.
One might says we can find a mistake simply by executing a spec, but if many people do the same, I think it's worth adding.

```ruby
# Bad
expect(foo).to has_key?(:bar)

# Good
expect(foo).to has_key(:bar)
```

**Comment by pirj** [comment]
RSpec already complains:
```
     NoMethodError:
       undefined method `has_key?' for #<RSpec::ExampleGroups::A "example at ./spec/a_spec.rb:2">
```
Why do we need a cop for that?
