### ISSUE TITLE
`RSpec/PendingWithoutReason` in 2.16.0 gives false positive in factories with `pending` attribute

### ISSUE THREAD

**Issue by RDeckard** [rubocop/rubocop-rspec#1565]
This is related to the "[False positive for `RSpec/PendingWithoutReason` in 2.16.0 when object has a method pending](https://github.com/rubocop/rubocop-rspec/issues/1549)" issue, because if those objects have any factory, we still have this _false positive_ offense:
![image](https://user-images.githubusercontent.com/5458964/212913925-2ac86ffa-e15f-48d7-bc2e-498ee6550654.png)

Not sure the best way to handle that. Indeed, in our project, we could exclude the `spec/factories` path for this cop in `.rubocop.yml`, but maybe this exclusion should be handled by the cop itself? Depending if you consider that using [factory_bot](https://github.com/thoughtbot/factory_bot) along with `rspec` is very usual, or where this responsibility stands. WDYT?

**Comment by pirj** [comment]
Fixed in 2.17
