### ISSUE TITLE
Should this gem be independent from rubocop-capybara?

### ISSUE THREAD

**Issue by Aqualon** [rubocop/rubocop-rspec#1570]
Hi, we use rspec in multiple of our projects and none of it uses capybara. Also the downloads of rspec on rubygems.org are much higher than for capybara, so I assume we are not the only ones.

I'd prefer to have only `rubocop-rspec` without the `rubocop-capybara` dependency. Also capybara can be used outside of rspec, so maybe it makes sense to treat them as independent from each other and people using capybara could add `rubocop-capybara` manually?

**Comment by pirj** [comment]
We intend to remove the dependency on `rubocop-capybara` in the next major release, 3.0, Real Soon™.
See #1519 and #1440 for details.
For SemVer reasons, we can't just remove all capybara cops in a minor release. Sorry for the inconvenience.
