### ISSUE TITLE
Check for empty line after `shared_context` and `shared_examples` blocks

### ISSUE THREAD

**Issue by czlee** [rubocop/rubocop-rspec#1582]
There are cops that check for empty lines after most blocks, like `describe`, `context` and `it`, but currently there isn't one (as far as I can tell) that checks for empty lines after `shared_context` or `shared_examples` blocks.

Minimal example:
``` rb
# frozen_string_literal: true

describe "empty line issue" do # rubocop:disable RSpec/DescribeClass
  shared_context "with context 1" do
    let(:foo) { "foo" }
  end
  shared_examples "examples" do
    it "has the expected value" do
      expect(foo).to eq "foo"
    end
  end
  context "with context 2" do
    include_context "with context 1"
    include_examples "examples"
  end

  context "with context 3" do
    let(:foo) { "foo" }

    include_examples "examples"
  end
end
```

**Expected outcome:** It should list two offenses:
1. No empty line after shared context `"with context 1"`
2. No empty line after shared examples `"examples"`

**Actual outcome:** No errors:
```
# rubocop spec/empty_line_after_shared_blocks_spec.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

**Versions:**
```
# rubocop -V
1.30.1 (using Parser 3.1.3.0, rubocop-ast 1.24.0, running on ruby 3.1.2 x86_64-linux-musl)
  - rubocop-performance 1.14.2
  - rubocop-rails 2.15.0
  - rubocop-rspec 2.11.1
 ```

I've checked the current master branch and searched other issues and can't see anything obvious intended to address this. I'll eventually (time indeterminate) look at submitting a PR for this if no one gets to it first, but wanted to raise the issue in case (1) there's something I've missed or (2) someone else gets to it first.

**Comment by pirj** [comment]
Technically, this can be achieved by changing `example_group?` to [`spec_group?`](https://github.com/rubocop/rubocop-rspec/blob/808ce138ca1a69e13fb33f0eff097c5a614b1b98/lib/rubocop/rspec/language.rb#L38) [here](https://github.com/rubocop/rubocop-rspec/blob/808ce138ca1a69e13fb33f0eff097c5a614b1b98/lib/rubocop/cop/rspec/empty_line_after_example_group.rb#L33).
Would you like to send a PR?

**Comment by czlee** [comment]
Sure! Might take a little while to find the bandwidth but would certainly be happy to give it a go.

Thanks for the tip! Any thought son whether we'd want to preserve backwards compatibility / make it configurable (whether to include shared groups) / make it a different cop?

**Comment by pirj** [comment]
Shared examples/contexts are an example groups, right, so the same cop could handle that?
I don't see why other rules should apply to whitespace around them.
