### ISSUE TITLE
PendingWithoutReason and one-liner syntax

### ISSUE THREAD

**Issue by schmijos** [rubocop/rubocop-rspec#1599]
@r7kamura do you (or someone else) have a suggestion about how to treat the one-liner syntax?

We did the following, which Rubocop now complains about:

```rb
context 'when parsed content does NOT pass … tests' do
  …

  # TODO: Test for the expected error messages as soon as validate_content is implemented
  xit { is_expected.not_to eq([]) }
end
```

**Comment by r7kamura** [comment]
I think such pending without passing any reason to RSpec should be an offense in this cop, as the test case clearly indicates it:

https://github.com/rubocop/rubocop-rspec/blob/c95e37b8f1043b7d469ed6832d2f04160bdb533e/spec/rubocop/cop/rspec/pending_without_reason_spec.rb#L355-L376

**Comment by schmijos** [comment]
I agree. But how would you configure the message?

There's no space on one line for long messages.
Would you suggest the programmer to not use a one-liner in this case?

**Comment by pirj** [comment]
Would something like this work for you, @schmijos ?
```ruby
  it(pending: 'Test for the expected error messages as soon as validate_content is implemented') { is_expected.not_to eq([]) }
```

**Comment by schmijos** [comment]
Actually yes, thank you. I found the following to be quite nice looking:

```rb
it(pending: <<~PENDING) { is_expected.to eq 20 }
  TODO: This is a pending example. It will be skipped until you remove the `pending: true` line.
        Ticket #1234 is not yet implemented.
        Product owner is still negotiating with the client.
PENDING
```
