### ISSUE TITLE
RSpec/Rails/*Http*

### ISSUE THREAD

**Issue by pirj** [rubocop/rubocop-rspec#1614]
We don't have a style that would enforce the use of predicate matchers:
```diff
- expect(response).to have_http_status(200)
- expect(response).to have_http_status(:ok)
+ expect(response).to be_ok
```

Research:
```
$ rg --no-ignore --hidden --count-matches 'have_http_status.200' | wc -l
126 # files, some file have more than one match

$ rg --no-ignore --hidden --count-matches 'have_http_status.:ok' | wc -l
91 # files, some file have more than one match

$ rg --no-ignore --hidden --count-matches 'be_ok' | wc -l
33 # files, some file have more than one match. Just a few are unrelated to responses

$ rg --no-ignore --hidden --count-matches 'be_successful' | wc -l
365 # files, some file have more than one match. All are related to responses
```

I'd say it could become the default style right away with such a magnitude of adoption.

[Mapping in Rack](https://github.com/rack/rack/blob/b172805895fc0490bf81e942487233e6771f4643/lib/rack/response.rb#L173).
[More](https://github.com/rack/rack/blob/8e8869d625e73e16b576b6d31b50208e9ec8002f/lib/rack/utils.rb#L485) - needs to be checked if additional ones work fine with predicate matchers.

I'm uncertain if it should be a new cop or a style for `HttpStatus`/`HaveHttpStatus`.

It feels that the cop could be strict or relaxed, e.g. suggest `be_ok` for 200 or `be_successful` for 200/201/202/204.
Should it enforce `be_redirect` for all 3xx codes? Or only in the relaxed mode?

**Comment by ydah** [comment]
Perhaps, support for predicate matchers, but we are adding support in this PR.
- https://github.com/rubocop/rubocop-rspec/pull/1527

**Comment by pirj** [comment]
Thanks for giving this another shot. It slipped my mind that there's already a ticket and a PR.
Closing as duplicate of #1148
