### ISSUE TITLE
Exception list for RSpec/IndexedLet

### ISSUE THREAD

**Issue by jrmhaig** [rubocop/rubocop-rspec#1628]
I considered adding a comment to #1626 but I think that this is a subtly different issue.

In the application I maintain we have things that have numbers in their names, so a number of the tests have test data with names like `scheme_9_offence` (for example). Would it be possible to have a configurable exception list so that we could have strings like `scheme_9`, `scheme_10`, etc, not considered as containing an index for the purpose of this cop?

**Comment by pirj** [comment]
I believe this is fixed in #1627 
Or do you mean that you have `let(:scheme_9)`/`let(:scheme_10)`? This would be solved in #1624, wouldn't it?

**Comment by jrmhaig** [comment]
Thanks. As it happens (I've been sifting through all the new offences that RSpec/IndexedLet has thrown up for me) all the `let`s that we have like this would be permitted by #1627. I had in mind things like `something_related_to_scheme_9`, which have the `scheme_9` as part of the name, but I see that this could be covered by #1624.

**Comment by jrmhaig** [comment]
I'm happy to close this. Thanks.
