### ISSUE TITLE
Cop Idea: Avoid allow Worker to receive(:perform_)

### ISSUE THREAD

**Issue by HarlemSquirrel** [rubocop/rubocop-rspec#1646]
Stubbing calls to enqueue workers can miss calls that use bad arguments such as those that do not serialize to JSON with Sidekiq 7.

Bad
```
allow(SomeWorker).to receive(:perform_async)
allow(SomeWorker).to receive(:perform_in)
```

Good
```
Sidekiq::Testing.fake!
```

**Comment by pirj** [comment]
I'm uncertain if we plan to include cops that would cover other, even very popular, libraries.
We've recently extracted capybara and factory_bot and plan to extract rspec-rails, as there are plenty of issues specific to the plain RSpec usage.

The idea for such an extension [was brought up already](https://github.com/toptal/active-job-style-guide/issues/6), and there's even a [`rubocop-sidekiq` repository](https://github.com/dvandersluis/rubocop-sidekiq).
Please do not get me wrong, I completely support your idea. I suggest sending a PR there.
You may also send a PR to the [style guide](https://github.com/toptal/active-job-style-guide#testing), I'll gladly accept it.

Thanks for bringing this up!
