### ISSUE TITLE
 Cop idea: Empty objects and be_empty matcher

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop-rspec#1661]
## Actual behavior

I have the code:

```ruby
RSpec.describe AdvertForm, type: :model do
  subject(:form) { described_class.new }

  specify do
    expect(form.foo).to eq([])
  end

  specify do
    expect(form.bar).to eq('')
  end

  specify do
    expect(form.car).to eq({})
  end
end
```

I run rubocop:

```bash
ydakuka@yauhenid:~/Work/project$ bin/rails_docker rubocop spec/forms/advert_form_spec.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

## Expected behavior

I like matchers. So I expected to have the following code:

```ruby
RSpec.describe AdvertForm, type: :model do
  subject(:form) { described_class.new }

  specify do
    expect(form.foo).to be_empty
  end

  specify do
    expect(form.foo).to be_a Array
  end

  specify do
    expect(form.bar).to be_empty
  end

  specify do
    expect(form.bar).to be_a String
  end

  specify do
    expect(form.car).to be_empty
  end

  specify do
    expect(form.car).to be_a Hash
  end
end
```

**Comment by pirj** [comment]
But how is the "expected" better?

**Comment by ydakuka** [comment]
1. readability

a) `eq([])` is very similar to `eq({})` and they can be easily confused, but no such problem with matchers.
b) English-like syntax.

2. common and consistent approach

```ruby
specify do
  expect(form.foo).to be_empty
end

specify do
  expect(form.foo).to be_a Array
end
```

is better than

```ruby
specify do
  expect(form.foo).to eq([])
end

specify do
  expect(form.foo).to eq(Array.new)
end

specify do
  expect(form.foo).to eq(Array.new(0))
end

specify do
  expect(form.foo).to eq(Array.new([]))
end
```

**Comment by bquorning** [comment]
I disagree. `expect(form.foo).to eq([])` and `expect(form.car).to eq({})` is also a common and consistent approach. The argument seems to hinge on

> `eq([])` is visually very similar to `eq({})` and they can be easily confused

which I also disagree with. This _could_ be solved by using e.g. `expect(form.foo).to eq(Array.new)` instead, but that would conflict with RuboCop’s `Style/EmptyLiteral` cop. Perhaps this problem can be solved by using [a different font](https://www.programmingfonts.org/)?
