### ISSUE TITLE
RSpec/Focus does not see the focus attribute on shared_examples

### ISSUE THREAD

**Issue by tmaier** [rubocop/rubocop-rspec#1673]
I had the following code and RSpec/Focus overlooked the `focus` attribute.

```ruby
RSpec.shared_examples 'Foable', focus: true do
  it { is_expected.to do things }
end
```

Gem Versions:
- rubocop-rspec (2.22.0)
- rubocop (1.54.2)
- rubocop-ast (1.29.0)

**Comment by pirj** [comment]
Would you like to submit a PR?
It's a matter of adding [`SharedGroups.all`](https://github.com/rubocop/rubocop-rspec/blob/b03a388ff8d16938d83f292289b5613c6d9a879f/lib/rubocop/rspec/language.rb#L181) [here](https://github.com/rubocop/rubocop-rspec/blob/b03a388ff8d16938d83f292289b5613c6d9a879f/lib/rubocop/cop/rspec/focus.rb#L53), extending the doc and adding an example.

**Comment by tmaier** [comment]
Done @pirj , see #1674
