### ISSUE TITLE
`RSpec/MetadataStyle` | `js: true` is invalid

### ISSUE THREAD

**Issue by phylor** [rubocop/rubocop-rspec#1711]
This is regarding the new `RSpec/MetadataStyle` enforcing symbols in metadata (added in #1497).

When writing feature specs in Rails, the following is a common pattern to enable the JavaScript driver:

```ruby
describe 'my test', js: true
it 'does something', js: true
```

The new cop fails on this pattern. Is this intended behavior? If it is, it would be great to have an example in the documentation.

The cop passes when a hash is used:

```ruby
enable_javascript_driver = {js: true}
describe 'my test', enable_javascript_driver
```

That feels a bit complex though, could well be intended though?

**Comment by pirj** [comment]
The cop suggests that
‘’’ruby
describe 'my test', :js
it 'does something', :js
‘’’
is the same thing. Just a different style.
Isn’t it?

**Comment by phylor** [comment]
> The cop suggests that ‘’’ruby describe 'my test', :js it 'does something', :js ‘’’ is the same thing. Just a different style. Isn’t it?

Oh, didn't know that. Yes, it is, thank you!

Do you think it makes sense to have a boolean example in the documentation?

**Comment by pirj** [comment]
> have a boolean example in the documentation?

Totally! A PR is welcome.

**Comment by phylor** [comment]
@pirj Sorry, there [already is an example for booleans](https://github.com/r7kamura/rubocop-rspec/blob/54d7b8e27cb70d464868169388523e18df1165c1/lib/rubocop/cop/rspec/metadata_style.rb#L12) :see_no_evil:
