### ISSUE TITLE
Partial Incorrect Flag/Bug: RSpec/MissingExampleGroupArgument

### ISSUE THREAD

**Issue by luke-hill** [rubocop/rubocop-rspec#1712]
This cop "arguably" incorrectly flags methods that are called `feature` (And probably others), that take no arguments but take a block. One such example is in `cucumber-ruby-core`

We have many method call-chains that look like the following... (I won't post all examples)

```
gherkin = gherkin('features/foo.feature') do
              feature do
                scenario do
                  step 'text'
                end
              end
            end
```

Would there be some way to not flag this. Possible suggestions are...

- Only detect at top of file?
- Provide an exclusion list for names (feature/specify/describe/context/it)
- Something else?

**Comment by luke-hill** [comment]
ping @bquorning - I'll close this based on the other work you've done. But I'm not 100% sure this will fix everything.

But I think "re-opening" any new items **after** upgrading to rubocop-rspec 3.0 is the best solution imo.

**Comment by luke-hill** [comment]
Hi @bquorning I found that I did raise this issue, and it is not fixed by rubocop-rspec 3.0.

Therefore I'm re-opening this. Sorry it's a very old issue. The problem still is here. Furthermore "other" cops also contribute to this and make the matter worse/more muddy

**Comment by luke-hill** [comment]
Other cops found which contribute / false flag.
- `RSpec/EmptyExampleGroup` -> same reason
- `RSpec/NoExpectationExample` -> same logic path I imagine, different reason (This one complains of `scenario do`)

**Comment by bquorning** [comment]
One option is to change the values for `RSpec/Language/ExampleGroups/Regular` to not include `feature`, and `RSpec/Language/ExampleGroups/Examples` to not include `scenario`, but of course those changes are global – meaning that rubocop-rspec will not recognize `feature` and `scenario` as RSpec example groups and examples at all.

**Comment by luke-hill** [comment]
I think the issue - ironically I was with @bbatsov this week at RubyConf.at and half mentioned these. Is that I recognise our DSL can conflict here. But we should/could ensure that the structure is diff.

i.e. I think this just looks for the word `scenario` whereas what it should error on is `scenario` keywords that are used instead of `it` blocks

Rinse/repeat for `feature` also.

Now the way I propose (Not 100% on this), to do this. Is that my definition are always inside `let` blocks.

i.e. the surrouding code is (Sorry for wall of text)

```
let(:gherkin_document) do
  gherkin do
    feature 'Feature name' do
      scenario 'The one that passes' do
        step 'passing'
      end

      scenario 'The one that fails' do
        step 'passing'
        step 'failing'
        step 'passing'
        step 'undefined'
      end
    end
  end
end
```

So because we're inside a `let` this "should" be able to go. I cannot have a `it` or `scenario` or `feature` or `context` or another RSpec keyword here. So please ignore this and treat it as something else.

EDIT: Read "inside a let" as "inside a let" OR "inside a context -> inside a let" ....... et al
