### ISSUE TITLE
RSpec/MetadataStyle: Use symbol style for metadata failing on boolean value

### ISSUE THREAD

**Issue by Alex-450** [rubocop/rubocop-rspec#1713]
`RSpec/MetadataStyle: Use symbol style for metadata` is triggered when setting a boolean value for metadata e.g:

```
RSpec.describe 'UI Component', type: :browser, js: true do
# Tests
end
```

Using a symbol for a boolean value doesn't seem to make sense.

**Comment by ydah** [comment]
Same Issue as below:
https://github.com/rubocop/rubocop-rspec/issues/1711

The cop suggests:
```diff
-RSpec.describe 'UI Component', type: :browser, js: true do
+RSpec.describe 'UI Component', type: :browser, :js do
# Tests
end
```
