### ISSUE TITLE
`RSpec/FilePath` split is disabled by default

### ISSUE THREAD

**Issue by splattael** [rubocop/rubocop-rspec#1717]
The changelog reads that `RSpec/FilePath` is "enabled by default" but it seems it isn't anymore.

Currently, users are forced to replace `RSpec/FilePath` with their alternatives when upgrading a minor release from 2.23.0 to 2.24.0. Is this expected or do we consider this a breaking change? :thinking: 

Refs https://gitlab.com/gitlab-org/ruby/gems/gitlab-styles/-/merge_requests/195 

/cc @ydah @bquorning

_Originally posted by @splattael in https://github.com/rubocop/rubocop-rspec/pull/1698#discussion_r1322578845_

**Comment by splattael** [comment]
From https://github.com/rubocop/rubocop-rspec/pull/1698#discussion_r1322601331:

@[bquorning](https://github.com/bquorning) [Sep 12, 2023](https://github.com/rubocop/rubocop-rspec/pull/1698#discussion_r1322601331)

> [...] I am not sure what is the preferred course of action – should we add the old cop back?

Good question! I was hoping we could turn the violation into a warning but unfortunately it's [supported yet](https://github.com/rubocop/rubocop/blob/1b7da8189e0aaebc15b906a41c46ed9f46aa15f4/lib/rubocop/config_obsoletion/cop_rule.rb#L23).

I see 2 options:
1. Fix the changelog and highlight that this is a breaking change
2. Enable `FilePath` by default and undo the split (in the `config/obsoletion.yml`) and highlight the tension of the cops in the changelog. 

Later (or in the  meanwhile):
- Allow split rules to emit warnings (via `severity: warning` in "cop rule", see above) in RuboCop repository
- Re-add the split configuration with `severity: warning`
- Make it a violation (instead of warning) in the next major release

Depending on what we consider a "breaking change" both options are possible :sweat_smile: 

WDYT?

**Comment by ydah** [comment]
As mentioned in the following PR
- https://github.com/rubocop/rubocop-rspec/pull/1710

How about proceeding as follows?
- Remove the configuration from config/obsoletion.yml once, since split would result in an error. (Patch version release)
- Release a version that warns if `RSpec/FilePath` is used (Next and subsequent releases)
- Remove `RSpec/FilePath` in the next major version update

**Comment by splattael** [comment]
@ydah :wave: 

> How about proceeding as follows?

This sounds great!

> I think it looks good. Perhaps it would be better to implement it before step2.

Yes, we could! However, we'd need to wait for the RuboCop version to be released and tweak the dependency here :shrug: 

For now, I only see either sticking with `rubocop-rspec 2.23.2` or accept the breaking change and remove `RSpec/FilePath` from `.rubocop.yml` per project.

**Comment by splattael** [comment]
Question for the maintainers: Since 2.24.0 has some potential for user confusion, I wonder if, after 2.24.1 was released with https://github.com/rubocop/rubocop-rspec/pull/1718 merged, we are considering yanking this release? :thinking:

**Comment by pirj** [comment]
> yanking this release

Quite unlikely. I see this as a regular bug fix.

We have had a [dependency issue situation](https://github.com/rubocop/rubocop-rspec/pull/1567) recently and planned to yank 2.18.0, but I think we didn’t and nobody complained.

**Comment by mockdeep** [comment]
I'm having trouble with this. If I disable the `RSpec/FilePath` rule, it complains that the rule has been deprecated, but if I remove references to it, it reports a violation. This is with `EnabledByDefault: true`.

**Comment by pirj** [comment]
Hey @mockdeep ! Interesting 🤔. Does it work the same way for you with the fix from #1718?

**Comment by mockdeep** [comment]
@pirj yeah, that fixes the issue for me. I need to handle both the `FilePath` and `SpecFilePathFormat` cops, but it doesn't cause an error preventing me from moving forward.

**Comment by bquorning** [comment]
v2.24.1 has been released, which I hope fixes the problem.

**Comment by edsu** [comment]
I'm confused, is the plan to still deprecate `RSpec/FilePath`?

**Comment by bquorning** [comment]
Yes, the `RSpec/FilePath` cop will be removed in v3.x (issue #1723). Since that would be a breaking change, the cop is still enabled for now. We _did_ disable it in v2.24.0 and then re-enable it in v2.24.1, which I imagine may cause some confusion. (At least it did for me 😅)

If you upgraded to v2.24.0 and started have the new cops `RSpec/SpecFilePathFormat` and `RSpec/SpecFilePathSuffix` explicitly enabled, you probably want to explicit _disable_ `RSpec/FilePath` after upgrading to v2.24.1.
