### ISSUE TITLE
Capybara/FeatureMethods identifies `given` calls from other DSLs.

### ISSUE THREAD

**Issue by ccutrer** [rubocop/rubocop-rspec#1719]
I have a spec that is exercising a DSL of its own:

```ruby
    let(:actor_class) do
      Class.new do
        extend AdheresToPolicy::ClassMethods

        set_policy do
          given { |actor| actor == "allowed actor" || actor.is_a?(user_class) }
          can :read

          given { |actor| actor == "allowed actor" }
          can :read
        end
      end
    end
```

and yet I'm getting `RSpec/Capybara/FeatureMethods: Use let instead of given.`

It seems like this cop should _only_ look for `given` calls immediately inside of `describe`, `context`, etc. blocks, and not in arbitrary code. At the least _not_ inside of a `let` itself.

`rubocop -V`:

```
1.22.0 (using Parser 3.0.2.0, rubocop-ast 1.12.0, running on ruby 2.7.2 x86_64-darwin20)
  - rubocop-performance 1.11.5
  - rubocop-rails 2.12.4
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.5.0
```

**Comment by pirj** [comment]
Sorry for the noise from transferring back and forth, it slipped my mind some Capybara cops remain here.

Speaking of the issue itself.
We have a check ‘return unless inside_example_group?(node)’, but it doesn’t seem to work when e.g ‘given’ is inside a ‘let’.

I would suggest changing this to ‘directly_under_example_group?’. To my best memory, we did this for some other cops already.

A PR is welcome.

**Comment by luke-hill** [comment]
If it's something that will be fixed in the short-medium term I'm happy to wait. I have 1000 other things to fix up in cucumber.

As for the why, the scenario/feature e.t.c. are generating the pickles for just that. a scenario or feature.

**Comment by luke-hill** [comment]
Apologies for coming in with more bad news / incorrections. But it seems `RSpec/NestedGroups` also flags this incorrectly.

Tidying up more things today and saw this:

```
spec/cucumber/core_spec.rb: RSpec/NestedGroups: Maximum example group nesting exceeded [4/3]. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/NestedGroups)
          feature do
          ^^^^^^^
```

Wider context

```
context 'without hooks' do
      let(:gherkin_document) do
        gherkin do
          feature 'Feature name' do
            scenario 'The one that passes' do
              step 'passing'
            end

            scenario 'The one that fails' do
              step 'passing'
              step 'failing'
              step 'passing'
              step 'undefined'
            end
          end
        end
      end
```

**Comment by bquorning** [comment]
I am closing this issue, since the RSpec/Capybara/FeatureMethods cop was removed in #1876 / v3.0.0.
