### ISSUE TITLE
Bug in `RSpec/SpecFilePathFormat` inline disables?

### ISSUE THREAD

**Issue by dgollahon** [rubocop/rubocop-rspec#1720]
Hi. I tried to upgrade to the latest version and convert my inline disables for `RSpec/FilePath` to `RSpec/SpecFilePathFormat` but they don't seem to work either on blanket disables early in the file or when attached to the end of a `RSpec.describe` line. Either way worked for `RSpec/FilePath`.

**Comment by bquorning** [comment]
@ydah, is this something you’d want to take a look at?

**Comment by ydah** [comment]
Ah, I see, because I changed it to add_global_offense. I'm wondering if this is a file name issue, and `Exclude` in rubocop.yml seems more appropriate for suppression than suppression in inline comments.

**Comment by ydah** [comment]
I thought it would be incongruous to comment on the class name to be tested and invalidate it when it is a file name issue. What do you think?

**Comment by ydah** [comment]
However, I don't feel strongly about it because I think compatibility is important.

**Comment by hjheath** [comment]
I've just hit this. I agree `Exclude` in rubocop.yml is more appropriate for file name issues.

However I'm hitting an issue where the rubocop.yml exclude configuration seems to be ignored for this new cop. Is this expected? Is this the same issue?

**Comment by dgollahon** [comment]
I prefer inline disables in all circumstances because if the file changes it is automatically reflected correctly or removed. Disabling via `Exclude` can easily go stale (it does not validate that the paths exist or still violate the cop). Since this used to work I would prefer it continue to work. I can move to an `Exclude` workflow but I think it's more confusing because most disables do not work this way. If it can only be disabled via `Exclude` it should probably tell you that in the output of the cop.
