### ISSUE TITLE
Cop idea: Avoid `example` keyword

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop-rspec#1732]
This is [dialect](https://github.com/rubocop/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/dialect.rb#L14) of `it` and `specify`. There is no information in the [guide](https://rspec.rubystyle.guide/) how to use `example`. I think it should be done [this way](https://docs.rubocop.org/rubocop-rspec/cops_rspec_capybara.html#rspeccapybarafeaturemethods).

```ruby
# bad
example 'answers success status' do
  expect(pinger.call).to eq(200)
end

# good
it 'answers success status' do
  expect(pinger.call).to eq(200)
end
```

**Comment by pirj** [comment]
‘it’ is certainly more common.
Related http://rspec.info/features/3-12/rspec-core/example-groups/aliasing/ - no info on example aliasing, though, but as you point out, it’s similar.
https://github.com/rubocop/rspec-style-guide/issues/64 On it vs specify

**Comment by ydah** [comment]
For example, in system spec I have a use case that uses `example`. So I don't want it to be uniformly avoided.

```ruby
example 'golden path to register user information' do
  #...
end
```

**Comment by pirj** [comment]
I think the [Dialect](https://github.com/rubocop/rubocop-rspec/blob/d94aca1dbcc77a648405cbb4f693c70f1a4e6abb/lib/rubocop/cop/rspec/dialect.rb#L30) cop would work for both cases, won’t it?

**Comment by ydah** [comment]
I think this should probably be mentioned in the Style guide about the use of `example` and `it`. You shouldn't create a cop that forces rubocop-rspec to do either, as shown below. So I'd like to close this issue. Thank you for your suggestion.

https://github.com/rubocop/rubocop-rspec/issues/1732#issuecomment-1888317404
