### ISSUE TITLE
Extract rspec-rails cops

### ISSUE THREAD

**Issue by bquorning** [rubocop/rubocop-rspec#1734]
Discussed in https://github.com/rubocop/rubocop-rspec/discussions/1440.

**Comment by bquorning** [comment]
@ydah In #1819 you hinted as wanting to do this extraction before the next minor release. Do you have some work in progress? 😄

**Comment by ydah** [comment]
@bquorning It's still WIP, but I'm creating a PR below.
https://github.com/rubocop/rubocop-rspec/pull/1830
