### ISSUE TITLE
RSpec/Capybara/FeatureMethods auto-correct is not safe

### ISSUE THREAD

**Issue by jeppester** [rubocop/rubocop-rspec#1753]
Given the following file:
```ruby
RSpec.feature 'Shifts report show' do
end
```

`RSpec/Capybara/FeatureMethods`  will auto-correct to:
```ruby
RSpec.expect 'Shifts report show' do
end
```

But that correction is not safe, since the example group now no longer has `type: :feature`, which can lead to certain helpers not getting loaded (which is how I discovered the issue).

Either the correction should lead to `type: :feature` getting added:
```ruby
RSpec.expect 'Shifts report show', type: :feature do
end
```

Or the cop should not have auto-correct marked as safe.

Rubocop version: 1.57.2
Rubocop-rspec version: 2.25.0

**Comment by ydah** [comment]
memo) `RSpec/Capybara/FeatureMethods` is a cop belonging to rubocop-rspec

**Comment by pirj** [comment]
Or the cop should not auto-correct top-level groups.

Thanks for reporting!

**Comment by bquorning** [comment]
I am closing this issue, since the RSpec/Capybara/FeatureMethods cop was removed in #1876 / v3.0.0.
