### ISSUE TITLE
Cop Idea: Only xstr in description

### ISSUE THREAD

**Issue by ydah** [rubocop/rubocop-rspec#1754]
If only `xstr` is passed to `describe`, `context` or `it`, the typo of `"` or `'` is suspect in many cases.
Also, if only `xstr` is, it may not be a good description of `describe` or `context` or `it`. What do you think?

```ruby
# bad
describe `time` do
end

# bad
context `time` do
end

# bad
it `time` do
end
```

**Comment by pirj** [comment]
Is this an issue from the real code? Why would anyone want to use that?

**Comment by ydah** [comment]
> Is this an issue from the real code? Why would anyone want to use that?

Yes, it is. Strictly speaking I saw the `it` case I encountered.

**Comment by pirj** [comment]
If those are typos, surely let’s add a cop to fix those

**Comment by r7kamura** [comment]
I guess someone who uses JavaScript template literals a lot wrote it by mistake. I've encountered this misuse too, but since this project was a Rails app, where `` Kernel#` `` is not used very often, I decided to enforce the `%x` literal.

```yaml
Style/CommandLiteral:
  EnforcedStyle: percent_x
```
