### ISSUE TITLE
`PendingWithoutReason` does not flag violations inside `shared_examples` and similar blocks

### ISSUE THREAD

**Issue by robinaugh** [rubocop/rubocop-rspec#1756]
We recently enabled `PendingWithoutReason` but it appears to miss usages of `xcontext` or `xit` inside certain blocks, i.e.:

```ruby
RSpec.describe SomeClass do
  xcontext 'this is a violation' do
    # ...
  end

  shared_examples 'description here' do
    xcontext 'this is not a violation' do
      # ...
    end
  end

  # helper block from papertrail gem
  with_versioning do
    xit 'this is not a violation either' do
      # ...
    end
  end
end
```

The output of `rubocop -V` is below:

```
╰─⠠⠵ rubocop -V
1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.2) [arm64-darwin22]
  - rubocop-capybara 2.19.0
  - rubocop-factory_bot 2.24.0
  - rubocop-rails 2.23.1
  - rubocop-rspec 2.25.0
```

**Comment by pirj** [comment]
Thanks for reporting.
Regarding shared groups, we miss a check of the parent [here](https://github.com/rubocop/rubocop-rspec/blob/fb85f8819a94e6d7e70313d89bf2500366642415/lib/rubocop/cop/rspec/pending_without_reason.rb#L106).

Speaking of third-party helpers, see this doc on how third-party gems can [augment our RSpec DSL conf](https://docs.rubocop.org/rubocop-rspec/third_party_rspec_syntax_extensions.html), and [this doc](https://docs.rubocop.org/rubocop-rspec/usage.html#rspec-dsl-configuration) on how to configure it for your project.

Would you like to send a PR to fix the shared example false negative?

**Comment by robinaugh** [comment]
> Thanks for reporting. Regarding shared groups, we miss a check of the parent [here](https://github.com/rubocop/rubocop-rspec/blob/fb85f8819a94e6d7e70313d89bf2500366642415/lib/rubocop/cop/rspec/pending_without_reason.rb#L106).
> 
> Speaking of third-party helpers, see this doc on how third-party gems can [augment our RSpec DSL conf](https://docs.rubocop.org/rubocop-rspec/third_party_rspec_syntax_extensions.html), and [this doc](https://docs.rubocop.org/rubocop-rspec/usage.html#rspec-dsl-configuration) on how to configure it for your project.
> 
> Would you like to send a PR to fix the shared example false negative?

Thanks for the quick reply @pirj! I've submitted https://github.com/rubocop/rubocop-rspec/pull/1757 to fix the shared example false negative, and I'll review the documentation you linked.
