### ISSUE TITLE
Expand Rails/HttpStatusCode pattern recognition?

### ISSUE THREAD

**Issue by ericproulx** [rubocop/rubocop-rspec#1760]
I'm using `rack-test` in a gem and the `Rails/HttpStatusCode` doesn't apply since the pattern is not `response.status` but `last_response.status`. Under `rails`, `response` is an `ActiveSupport::TestResponse` which includes `Rack::Response::Helpers`. That way, we can use `be_successful` and all other `be_***`. On the other hand, `rack-test` is using the native `Rack::MockResponse` which is also including `Rack::Response::Helpers` but defines `last_response` instead of `response`. 

Both cases can use the `be_***` matchers with RSpec but the cop is just looking for the `response` pattern. Is there a way to configure the cop ?

**Comment by pirj** [comment]
Would you be interested in extending the cop?
Wondeting if `last_response` is available in Rails, too?

Replacing `:response` with `{:response :last_response}` [here](https://github.com/rubocop/rubocop-rspec/blob/958a3c44cbe847af7f023506520be48066c5dd23/lib/rubocop/cop/rspec/rails/have_http_status.rb#L31) will be the key change.

**Comment by ericproulx** [comment]
Of course, that's the easy part. Also, I might check with the gem to alias `last_reponse` with `response`

**Comment by pirj** [comment]
My apologies, I was under the impression that it’s the rack-test that defines last_response. What other gem is it? I’m uncertain if we want to change the cop for everyone if it’s not rack or rack-test.

**Comment by ericproulx** [comment]
Sorry for the confusion. `last_response` is defined by `rack-test`

**Comment by pirj** [comment]
In this case, a PR is welcome. There’s no doubt in the width of rack-test adoption
