### ISSUE TITLE
`RSpec/RedundantPredicateMatcher` says `Use all instead of be_all.` but it cannot

### ISSUE THREAD

**Issue by znz** [rubocop/rubocop-rspec#1766]
`RSpec/RedundantPredicateMatcher` says `Use all instead of be_all.`
But it cannot replace when the argument of `be_all` is not a matcher.

```ruby
# frozen_string_literal: true

require_relative 'spec_helper'

describe do
  it do
    a = [2, 2]
    # expect(a).to all(a.size) # This raises NoMethodError: undefined method `matches?' for 2:Integer
    expect(a).to be_all(a.size) # `RSpec/RedundantPredicateMatcher: Use all instead of be_all.`
  end
end
```

**Comment by pirj** [comment]
`expect(a).to all be(a.size)` should work.

**Comment by znz** [comment]
`all be` works for me.
So  I want that examples include `be_all` and its replacement in <https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecredundantpredicatematcher>.
