### ISSUE TITLE
RSpec/ExampleWording incorrectly correct some texts

### ISSUE THREAD

**Issue by mobilutz** [rubocop/rubocop-rspec#1767]
This is a very minor bug, but something to at least look into.

The problem is, that some texts are being incorrectly corrected. See examples:
```ruby
it 'will properly do something' do
  ...
end

# is autoconverted to 
it 'properlies do something' do
  ...
end
```

The same happens with `should` of course, as the code is the same.

I guess there are other adverbs that lead to the same problem.

```bash
$ rubocop -V
1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.2) [x86_64-darwin22]
  - rubocop-capybara 2.20.0
  - rubocop-factory_bot 2.25.0
  - rubocop-performance 1.20.1
  - rubocop-rails 2.23.1
  - rubocop-rspec 2.26.0
```

**Comment by ydah** [comment]
Since the following change is included in this release, does the offense appear to be correct.
- https://github.com/rubocop/rubocop-rspec/pull/1752

**Comment by mobilutz** [comment]
@ydah I just saw these changes after upgrading the `v2.26.0`

The problem is not that it autocorrects, which it does perfectly for many things, the problem is that it converts `will properly do something` to `properlies do something` which is not correct english.

**Comment by ydah** [comment]
Certainly this may not be suitable for autocorrection; rubocop cannot know if the result of removing will or should is the correct English sentence. Maybe we should change to Unsafe for autocorrection. @rubocop/rubocop-rspec What do you think?

**Comment by pirj** [comment]
What does “unsafe mean”? Does it apply to test code output messages? I don’t think so.

**Comment by bquorning** [comment]
I agree that this is an inconvenient autocorrect, but not an unsafe one.

**Comment by mobilutz** [comment]
> I agree that this is an inconvenient autocorrect, but not an unsafe one.

I agree with this, that is also why I said this is minor.

Maybe there could be exceptions like 'properly ' where adding the 's' at the end will not be done.

**Comment by pirj** [comment]
I wish there was a performant way to distinguish adverbs from verbs. We could autocorrect to ‘it “properly does something”’ then.

**Comment by bquorning** [comment]
To fix this problem properly, I think we’d need to bundle a library that specializes in natural language processing. In other words, I believe fixing this problem is out of scope for rubocop-rspec.

**Comment by pirj** [comment]
Agreed. I believe we’re coming to a conclusion to close this?
