### ISSUE TITLE
RSpec/RepeatedSubjectCall flags a false positive

### ISSUE THREAD

**Issue by luizkowalski** [rubocop/rubocop-rspec#1821]
Hey 👋🏻 

I have a test like this:

```ruby
subject { described_class.new(url) }
...
context "remaining is exhausted" do
  let(:remaining) { 0 }

  it "fails on the next call" do
    expect { subject.call }.not_to raise_error
    expect { subject.call }.to raise_error(RateLimiter::LimitedError)
  end
end
...
```

from what I understand, `subject` is memorized; in this case, `described_class.new(url)` but the `.call` is not memoized. I know that because this test is currently passing. 

I don't think this cop should flag such cases (when the subject invokes another method).

**Comment by franzliedke** [comment]
Ha, I just came here to report the same problem.

Another example with false positives:

```ruby
expect { subject.method1 }.to raise_error(SomeException)
expect { subject.method2 }.to raise_error(SomeException)
expect { subject.method3 }.to raise_error(SomeException)
```

**Comment by tobiasamft** [comment]
Hello 👋 , I just wanted to add another example which could be worth mentioning:

```ruby
class Something
  def work
    private_method
  end

  private

  def private_method
    # some call that may raise an error
  end
end
```

```ruby
describe Something do
  subject { described_class.new }

  describe '#work' do
    it 'raises' do
      allow(subject).to receive(:private_method).and_raise(
        StandardError,
        'error message',
      )
      expect { subject.work }.to raise_error(StandardError, 'error message')
    end
  end
end
```

**Comment by sgessa** [comment]
Not sure if this case is already covered but seems a false positive to me.
The following example is called from a shared example.

```ruby
it 'raises an error if country GB' do
  if country_id == 'GB'
    expect { action }.to raise_error(ArgumentError)
  else
    expect { action }.not_to raise_error
  end
end
```

**Comment by pirj** [comment]
The expectation inside the "else" clause doesn’t match the docstring. It deserves to be extracted to a separate co text or example.
Thus, no need for an `if` and no false positive.
