### ISSUE TITLE
RSpec/Rails/HaveHttpStatus autofix broke test suite

### ISSUE THREAD

**Issue by VitaliySerov** [rubocop/rubocop-rspec#1823]
Hey guys I have a sinatra application:

https://github.com/ONLYOFFICE-QA/sinatra-post-to-redis

some specs in it looks like this:

```
it 'allows send post notification' do
    post '/', notification: 'hello rspec'

    expect(last_response.status).to eq 200
  end
  ```

after upgrading rubocop-rspec and applying auto-update expect line was changes to `expect(last_response).to have_http_status :ok`

And this changes execution of rspec tests, seems that sinatra apps are not aware of those:

```
  1) SinatraPostToRedis allows send post notification
     Failure/Error: expect(last_response).to have_http_status :ok
       expected #<Rack::MockResponse:0x00007f68ae7fea68 @original_headers={"Content-Type"=>"text/html;charset=utf-8",....0/gems/rack-2.2.8.1/lib/rack/response.rb:287>, @block=nil, @body=["OK"], @buffered=true, @length=2> to respond to `has_http_status?`
     # ./spec/sinatra_post_to_redis/sinatra_post_to_redis_spec.rb:10:in `block (2 levels) in <top (required)>'
```
You can see changes here:

https://github.com/ONLYOFFICE-QA/sinatra-post-to-redis/pull/600/commits/5eb9d7fb1e9d086a6e931a3fe2c807bb8dd88fe2

**Comment by ydah** [comment]
As the name implies, it's a cop in the Rails department, so we recommend departmental invalidation in .rubocop.yml as follows. How about setting?

```yaml
RSpec/Rails:
  Enabled: false
```

**Comment by VitaliySerov** [comment]
Yeah, of course I can disable it

But maybe there should be some fail-safe mechanism in `rubocop-rspec` that non-rails application will not be detected by Rspec/Rails cop?

If it's not possible - I think there is should be a line in readme "please disable Rspec/Rails in case you use `rubocop-rspec` in non-rails env`

**Comment by ydah** [comment]
Soon, the RSpec/Rails cop will be cut off to another gem. Users will be able to hire only the departments they need.
https://github.com/rubocop/rubocop-rspec/issues/1734

**Comment by VitaliySerov** [comment]
@ydah All right, seems like a good solution, but I think we can keep my issue opened until the migration is done?

**Comment by ydah** [comment]
If this is a good solution, I think this issue can be closed because it overlaps with the following issue.
https://github.com/rubocop/rubocop-rspec/issues/1734

**Comment by VitaliySerov** [comment]
Ok, will close it

Thanks for your work :)
