### ISSUE TITLE
Trusted publishing

### ISSUE THREAD

**Issue by bquorning** [rubocop/rubocop-rspec#1827]
I’m looking into using [RubyGems’ trusted publishing](https://guides.rubygems.org/trusted-publishing/adding-a-publisher/) to push a gem from a GitHub action ([example](https://github.com/segiddins/rubygems-await/blob/main/.github/workflows/push_gem.yml)). @rubocop/rubocop-rspec Do you see any downsides to this approach?

**Comment by ydah** [comment]
I think there doesn't seem to be any particular downsides.
