### ISSUE TITLE
Extract RSpec Rails cops change caused regression if `rack` is not installed.

### ISSUE THREAD

**Issue by ntkme** [rubocop/rubocop-rspec#1847]
I don't use rails/rack in my project, and I'm seeing the following error with `rubocop-rspec 2.28.0` + `rubocop-rspec_rails 2.28.1`:

```
Error: unrecognized cop or department RSpecRails/HttpStatus found in vendor/bundle/ruby/3.3.0/gems/rubocop-rspec_rails-2.28.1/config/default.yml
Did you mean `RSpecRails/HaveHttpStatus`?
```

It looks like this is an issue because `RSpecRails/HaveHttpStatus` is conditionally loaded, and do not exist if `rack` is not installed: https://github.com/rubocop/rubocop-rspec_rails/blob/b141576cf6fb1f75bb3e446b96d4c4f8266cc161/lib/rubocop/cop/rspec_rails_cops.rb#L6-L10

```
begin
  require_relative 'rspec_rails/http_status'
rescue LoadError
  # RSpecRails/HttpStatus cannot be loaded if rack/utils is unavailable.
end
```

**Comment by ntkme** [comment]
Close as a dup of #1486.

**Comment by ydah** [comment]
FYI, A fixed version has been released:
https://github.com/rubocop/rubocop-rspec_rails/releases/tag/v2.28.2

Thank you for your report.
