### ISSUE TITLE
Docs namespaces don't match the real ones

### ISSUE THREAD

**Issue by smcabrera** [rubocop/rubocop-rspec#1874]
We're getting messages like this after a recent update

```
RSpec/Rails/HaveHttpStatus has the wrong namespace - replace it with RSpecRails/HaveHttpStatus
```

But we noticed that the docs continue to have the old namespace

https://docs.rubocop.org/rubocop-rspec/2.29/cops_rspec_rails.html#rspecrailshavehttpstatus

![CleanShot 2024-05-01 at 16 49 44@2x](https://github.com/rubocop/rubocop-rspec/assets/4121835/e5b89145-adcf-4f45-ab67-31fb6115beb6)

Seems like the docs need to be updated unless I'm misunderstanding something.

**Comment by ydah** [comment]
We get a warning, but the cop in the old namespace RSpec/Rails/HaveHttpStatus is still there. This is left for backward compatibility.
Therefore, I believe the documentation should also continue to be kept until the next major version of the these cop is removed.

**Comment by pirj** [comment]
Just to confirm, are those warnings? Or does this break your rubocop runs?

Closing assuming the former.
