### ISSUE TITLE
We also need support `AutoCorrect: contextual` option for LSP

### ISSUE THREAD

**Issue by ydah** [rubocop/rubocop-rspec#1883]
- https://github.com/rubocop/rubocop/pull/12657

For example, if `RSpec/Focus` is enabled, we will always have `focus` removed by the LSP.
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecfocus

**Comment by bquorning** [comment]
As far as I can tell, this is the current state of autocorrection for the different cops, sorted by “Always”, “Always (unsafe)”, “No”:

Always

- [ ] `RSpec/AlignLeftLetBrace`
- [ ] `RSpec/AlignRightLetBrace`
- [ ] `RSpec/BeEmpty`
- [ ] `RSpec/BeNil`
- [ ] `RSpec/ChangeByZero`
- [ ] `RSpec/ClassCheck`
- [ ] `RSpec/ContainExactly`
- [ ] `RSpec/ContextMethod`
- [ ] `RSpec/Dialect`
- [ ] `RSpec/DuplicatedMetadata`
- [ ] `RSpec/EmptyHook`
- [ ] `RSpec/EmptyLineAfterExample`
- [ ] `RSpec/EmptyLineAfterExampleGroup`
- [ ] `RSpec/EmptyLineAfterFinalLet`
- [ ] `RSpec/EmptyLineAfterHook`
- [ ] `RSpec/EmptyLineAfterSubject`
- [ ] `RSpec/EmptyMetadata`
- [ ] `RSpec/EmptyOutput`
- [ ] `RSpec/Eq`
- [ ] `RSpec/ExampleWording`
- [ ] `RSpec/ExcessiveDocstringSpacing`
- [ ] `RSpec/ExpectActual`
- [ ] `RSpec/Focus`
- [ ] `RSpec/HookArgument`
- [ ] `RSpec/HooksBeforeExamples`
- [ ] `RSpec/ImplicitExpect`
- [ ] `RSpec/ImplicitSubject`
- [ ] `RSpec/InstanceSpy`
- [ ] `RSpec/IsExpectedSpecify`
- [ ] `RSpec/ItBehavesLike`
- [ ] `RSpec/LeadingSubject`
- [ ] `RSpec/LetBeforeExamples`
- [ ] `RSpec/MatchArray`
- [ ] `RSpec/MetadataStyle`
- [ ] `RSpec/MultipleSubjects`
- [ ] `RSpec/NotToNot`
- [ ] `RSpec/ReceiveCounts`
- [ ] `RSpec/ReceiveNever`
- [ ] `RSpec/RedundantAround`
- [ ] `RSpec/RedundantPredicateMatcher`
- [ ] `RSpec/ReturnFromStub`
- [ ] `RSpec/ScatteredLet`
- [ ] `RSpec/ScatteredSetup`
- [ ] `RSpec/SharedContext`
- [ ] `RSpec/SharedExamples`
- [ ] `RSpec/SingleArgumentMessageChain`
- [ ] `RSpec/SortMetadata`
- [ ] `RSpec/VariableDefinition`
- [ ] `RSpec/Yield`

Always (Unsafe)

- [ ] `RSpec/BeEq`
- [ ] `RSpec/BeEql`
- [ ] `RSpec/DescribedClass`
- [ ] `RSpec/EmptyExampleGroup`
- [ ] `RSpec/ExpectChange`
- [ ] `RSpec/PredicateMatcher`
- [ ] `RSpec/ReceiveMessages`
- [ ] `RSpec/VerifiedDoubleReference`

No

- [ ] `RSpec/AnyInstance`
- [ ] `RSpec/AroundBlock`
- [ ] `RSpec/Be`
- [ ] `RSpec/BeforeAfterAll`
- [ ] `RSpec/ContextWording`
- [ ] `RSpec/DescribeClass`
- [ ] `RSpec/DescribedClassModuleWrapping`
- [ ] `RSpec/DescribeMethod`
- [ ] `RSpec/DescribeSymbol`
- [ ] `RSpec/ExampleLength`
- [ ] `RSpec/ExampleWithoutDescription`
- [ ] `RSpec/ExpectInHook`
- [ ] `RSpec/ExpectOutput`
- [ ] `RSpec/IdenticalEqualityAssertion`
- [ ] `RSpec/ImplicitBlockExpectation`
- [ ] `RSpec/IndexedLet`
- [ ] `RSpec/InstanceVariable`
- [ ] `RSpec/IteratedExpectation`
- [ ] `RSpec/LeakyConstantDeclaration`
- [ ] `RSpec/LetSetup`
- [ ] `RSpec/MessageChain`
- [ ] `RSpec/MessageExpectation`
- [ ] `RSpec/MessageSpies`
- [ ] `RSpec/MissingExampleGroupArgument`
- [ ] `RSpec/MultipleDescribes`
- [ ] `RSpec/MultipleExpectations`
- [ ] `RSpec/MultipleMemoizedHelpers`
- [ ] `RSpec/NamedSubject`
- [ ] `RSpec/NestedGroups`
- [ ] `RSpec/NoExpectationExample`
- [ ] `RSpec/OverwritingSetup`
- [ ] `RSpec/Pending`
- [ ] `RSpec/PendingWithoutReason`
- [ ] `RSpec/RemoveConst`
- [ ] `RSpec/RepeatedDescription`
- [ ] `RSpec/RepeatedExample`
- [ ] `RSpec/RepeatedExampleGroupBody`
- [ ] `RSpec/RepeatedExampleGroupDescription`
- [ ] `RSpec/RepeatedIncludeExample`
- [ ] `RSpec/RepeatedSubjectCall`
- [ ] `RSpec/SkipBlockInsideExample`
- [ ] `RSpec/SpecFilePathFormat`
- [ ] `RSpec/SpecFilePathSuffix`
- [ ] `RSpec/StubbedMock`
- [ ] `RSpec/SubjectDeclaration`
- [ ] `RSpec/SubjectStub`
- [ ] `RSpec/UndescriptiveLiteralsDescription`
- [ ] `RSpec/UnspecifiedException`
- [ ] `RSpec/VariableName`
- [ ] `RSpec/VerifiedDoubles`
- [ ] `RSpec/VoidExpect`

Should we start adding checkboxes to the ones we want to be contextual?

**Comment by ydah** [comment]
Basically, I think `always` is fine. So, let's list only the obvious annoyances like `RSpec/Focus` as a `contextual` list. If the cop that requires `contextual` is not `contextual`, it doesn't break the existing behavior. WDYT?

**Comment by bquorning** [comment]
What about cops like RSpec/ScatteredLet and RSpec/ScatteredSetup, wouldn’t they potentially move the code a person is currently editing?
