### ISSUE TITLE
Consider if any cops should be renamed

### ISSUE THREAD

**Issue by bquorning** [rubocop/rubocop-rspec#1887]
Now that the next major release draws closer, I think it’s time to consider whether all of our cops are properly named.

Previous to their v1.0.0, RuboCop did a massive cop rename (see rubocop/rubocop#6983, rubocop/rubocop#7077, rubocop/rubocop#7468) and I wonder if we ever truly went over our cop names. Just one example:

- RSpec/DuplicatedMetadata
- RSpec/EmptyMetadata
- RSpec/MetadataStyle
- RSpec/SortMetadata

These four cops all check metadata, but three are named FooMetadata and one is MetadataFoo. Should one or three (or zero) be renamed?

**Comment by bquorning** [comment]
cc @rubocop/rubocop-rspec

**Comment by bquorning** [comment]
Gotcha, you are correct that renaming might cause more pain than joy among our users. But perhaps we should copy [that section from development.adoc](https://github.com/rubocop/rubocop/blob/b409e45693d51c8e2d32bf6fd5f6fe644beefdbd/docs/modules/ROOT/pages/development.adoc#choose-a-name) into our repository and think a _little_ more about cop names before adding them? 😅

**Comment by pirj** [comment]
That makes sense. I also commit to extracting the guideline part in hope to merge it

**Comment by dvandersluis** [comment]
FYI it is now possible to configure renames as warnings, and existing (pre-rename) configuration should be used: https://github.com/rubocop/rubocop/pull/14006
