### ISSUE TITLE
Cleanup warning: `max=` is deprecated. Use `exclude_limit <ParameterName>` instead.

### ISSUE THREAD

**Issue by jdehaan** [rubocop/rubocop-rspec#1937]
With rubocop version 1.65.0, running the cop yields warning messages on the console:

```
rubocop-rspec-3.0.2/lib/rubocop/cop/rspec/multiple_memoized_helpers.rb:97: \
   warning: `max=` is deprecated. Use `exclude_limit <ParameterName>` instead.
```

There is some adaptation needed, but probably some care about dependencies or version compatibility needs to be taken to allow interoperability between versions if that is wanted.

**Comment by koic** [comment]
This warning will be resolved by https://github.com/rubocop/rubocop-rspec/pull/1936. It should be suppressible by upgrading after the release.
