### ISSUE TITLE
RSpec/LetSetup trips when using let! object in other let

### ISSUE THREAD

**Issue by thisismydesign** [rubocop/rubocop-rspec#1944]
The following trips `RSpec/LetSetup` but I think it's a valid use case:
```
context 'when the name is the same but publisher is different' do
  let!(:existing_content) { create(:content) }
  let(:content) { build(:content, name: existing_content.name) }

  it 'is valid' do
    expect(content).to be_valid
  end
end
```

`existing_content` is not used in the test but it's used in another `let`

**Comment by pirj** [comment]
Do you mind sharing what the offence is?

**Comment by thisismydesign** [comment]
I probably misunderstood and there wasn't an offense for this piece of code, apologies.
