### ISSUE TITLE
Negated predicate marker is not strict enough

### ISSUE THREAD

**Issue by marcandre** [rubocop/rubocop-rspec#1966]
I'm just realizing that the following will unfortunately pass if `foo?` returns `nil`, which I believe is usually what one does not want.

```ruby
expect(something).not_to be_foo
```

Unless I'm mistaken, there is no cop to detect this.

Is there a better way than to write the following?

```ruby
expect(something.foo?).to be false
```

Ideally, a cop would also catch and autocorrect `is_expected.not_to be_foo` to `expect(subject.foo?).to be false`. It would also deal with `be_foo(:some_args)`.

**Comment by pirj** [comment]
I think if this can he enforced on RSpec side, it should. I recall this [strict predicate option that you’ve contributed](https://github.com/rspec/rspec-expectations/blob/838952dc1416c943e7933684c47249a77481e7f5/lib/rspec/expectations/configuration.rb#L194), do you think the `not_to be_foo` would pass for `nil`?
If so, I’d say that it is not strict enough.

Also, historically, rubocop-rspec considers those things that can be detected with RSpec warnings or failures as non-goals.
But I’m open to reconsider this if there’s a case.

**Comment by marcandre** [comment]
Ah, I doubled checked the documentation, and indeed one can optionally define `does_not_match?`, which would allow that.

I opened https://github.com/rspec/rspec-expectations/issues/1487 🤞

I'm surprised this never came up before (at least I didn't see an issue about it).

**Comment by marcandre** [comment]
Sorry for the noise. Simply need to turn on the config for `strict_predicate_matchers`
