### ISSUE TITLE
Cop idea: change example length from counting lines to statements

### ISSUE THREAD

**Issue by jcoyne** [rubocop/rubocop-rspec#249]
Example:
```ruby
    it "spawns CreateWorkJobs for each work" do
      expect(CreateWorkJob).to receive(:perform_later).with(user,
                                                            "GenericWork",
                                                            {
                                                              keyword: [],
                                                              title: ['File One'],
                                                              resource_type: ["Article"],
                                                              uploaded_files: ['1']
                                                            },
                                                            child_log).and_return(true)
      expect(CreateWorkJob).to receive(:perform_later).with(user,
                                                            "GenericWork",
                                                            {
                                                              keyword: [],
                                                              title: ['File Two'],
                                                              resource_type: ["Image"],
                                                              uploaded_files: ['2']
                                                            },
                                                            child_log).and_return(true)
      subject
    end
```

This has 3 statements, which seems like a reasonable number for an example. But due to the way it's formatted (which I believe contributes to good readability *) it has 17 lines, which causes the cop to fail. Would it be possible to count the number of statements instead of lines?

\* Kevlin Henney - Seven Ineffective Coding Habits of Many Programmers https://vimeo.com/97329157#t=14:36

**Comment by backus** [comment]
I think line length and statement complexity are probably both decent heuristics with edge cases that will be obviously wrong in some cases. What do you think abuot a separate cop instead like `RSpec/ExampleComplexity` that might do something like this?

**Comment by jfelchner** [comment]
Now that I'm looking at this I'm wondering if just using rubocop's built-in `PerceivedComplexity`, `AbcSize`, `CyclomaticComplexity` cops might be good enough here.

**Comment by jfelchner** [comment]
FWIW, rubocop's line number cops now allow exceptions for hashes, arrays, and heredocs.  Perhaps it's abstracted enough that this cop could take advantage of it as well. See [here](https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/mixin/code_length.rb#L54)

**Comment by Darhazer** [comment]
Since ExampleLength supports the CountAsOne option for arrays and hashes, perhaps we can close this?

**Comment by pirj** [comment]
Makes sense 👍 @bquorning ?

**Comment by bquorning** [comment]
Yes, I agree. As @Darhazer mentioned, the RSpec/ExampleLength cop can be configured with the `CountAsOne` option (with an array of one or more of `array`, `hash` and `heredoc`). (The documentation at https://docs.rubocop.org/rubocop-rspec/2.9/cops_rspec.html#countasone-array-heredoc doesn’t mention the `hash` option, which we should probably get fixed.)
