### ISSUE TITLE
Cop idea: [Factory girl] Enforce consistent usage of parentheses in factory girl methods

### ISSUE THREAD

**Issue by Darhazer** [rubocop/rubocop-rspec#416]
I'm working on a code base where I have both styles of using factory:
`create(:user, name: 'John')` and `create :user, name: 'John;`
it will be good if one of those styles is required.

Note: parentheses may be required in nested associations no matter the style, like in:
`create :account, user: create(:user, name 'John')`

**Comment by andyw8** [comment]
I feel this is more general style choice of whether method calls should use parentheses or not. Perhaps it would be better to be have this in RuboCop itself?

**Comment by Darhazer** [comment]
IMO it's OK to have different method call style for different DSLs. `Syle/MethodCallWithArgsParentheses` looks for such, but we disable it in the specs, as I can't imagine writting `it('some description')` or even `allow(Foo).to(receive(:bar))`

**Comment by andyw8** [comment]
I dug a little further. RuboCop does indeed already have a cop for this kind of thing, although it's disabled by default:

http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/MethodCallWithArgsParentheses

You can tell it which methods to ignore, e.g.:

```
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - it
    - create
    - describe
```

Currently this can only be used to enforce the presence of parenthesis, rather than their absense. But I think it be a fairly simple change to RuboCop if you need that, e.g. by adding an `EnforcedMethods` option.

**Comment by andyw8** [comment]
Nevermind, just saw your reply above.

**Comment by Drowze** [comment]
I would love a cop enforcing this. There is usually no standard when regarding factorybot DSL

**Comment by pirj** [comment]
I think [this rule](https://github.com/rubocop-hq/ruby-style-guide/#method-invocation-parens-internal-dsl) applies to FactoryGirl.

So if there's no such cop in RuboCop itself (couldn't find one quickly), it might be a good idea to implement it there.

**Comment by dgollahon** [comment]
I don't know if the rule accounts for this at all, but I usually use parentheses with a "dsl" _unless_ it's in a class context / macro. So, for the `validates` example, I usually write it as the guide recommends, but for almost all the rspec methods that aren't `describe`, `context`, `it`, or `to`, for instance, i typically use parentheses. Like @Darhazer is saying, I don't think a universal rule necessarily matches all DSLs.

Personally, I always write factories with parentheses and that seems like the better default to me (disclaimer: i'm trending towards more parens in most places), but this could easily be configurable and I expect it will be somewhat controversial either way.

**Comment by vmakoed** [comment]
Any update with this?

**Comment by pirj** [comment]
@vmakoed Pull request is always welcome!

I guess this cop should have a style option whether to set parantheses or not.
