### ISSUE TITLE
Capybara/FeatureMethods - improve the suggestion?

### ISSUE THREAD

**Issue by andyw8** [rubocop/rubocop-rspec#505]
I've just upgraded to the latest gem so ran into this.

The `Capybara/FeatureMethods` cop suggests that `scenario 'with OAuth'` should be changed to `it 'with OAuth'`. I feel this is bad advice. When RSpec is run with `--format documentation`, the specs should give a readable, plain-language overview of the behaviour. `it with OAuth` is nonsensical.

Even though `scenario` is an alias of `it`, I feel that it would better map to a combination of `context` and `it`. For example:

```ruby
scenario "with OAuth" do
  sign_in_with_oauth
  expect(page).to have_text("Welcome")
end
```

Would become:

```ruby
context "with OAuth" do
  it "authenticates successfully" do
    sign_in_with_oauth
    expect(page).to have_text("Welcome")
  end
end
```

Any thoughts on this @rspeicher?

**Comment by rspeicher** [comment]
@andyw8 That would improve the documentation format, but so would `it "authenticates with OAuth successfully"`.

I'm not sure the gem should be suggesting the `context`/`it` combo, because not every description needs it, and it would make autocorrecting extremely difficult (where would "authenticates successfully" come from in this case?)

**Comment by andyw8** [comment]
Yes, "authenticates with OAuth successfully" would be fine.

I think trying to auto-correct from the Capybara DSL to plain RSpec is going to be difficult in many cases. I wonder if it's better not to try, rather than make bad corrections?

**Comment by rspeicher** [comment]
Even making bad corrections/suggestions would be difficult, since we're basically parsing English (or any other natural language) at that point, right?

**Comment by andyw8** [comment]
Indeed. So maybe the cop should just report the problem rather than try making any fix, e.g. `Prefer native RSpec over Capybara's acceptance test DSL ('given')`

cc @backus for any thoughts.

**Comment by mvz** [comment]
See also #538 for another issue with this cop's suggestions.

**Comment by bquorning** [comment]
I am closing this issue, since the RSpec/Capybara/FeatureMethods cop was removed in #1876 / v3.0.0.
