### ISSUE TITLE
Capybara/FeatureMethods conflicts with RSpec/DescribeClass in feature specs

### ISSUE THREAD

**Issue by mvz** [rubocop/rubocop-rspec#538]
rubocop-rspec  should support rspec-rails' feature specs, however:

The following gives a `RSpec/DescribeClass` offense:
```
RSpec.describe 'user does foo', type: :feature do
  it 'succesfully foos the bar' do
    ...
  end
end
```

The following gives a Capybara/FeatureMethods offense:
```
RSpec.feature 'user does foo', type: :feature do
  scenario 'succesfully fooing the bar' do
    ...
  end
end
```

**Comment by Darhazer** [comment]
@mvz would #593 work for you?

**Comment by mvz** [comment]
@Darhazer I'm not sure. I was going to write a response based on reasoning, but I concluded I need to give this a try and see how it works out.

**Comment by mvz** [comment]
@Darhazer I'm afread 75baab383d3d60d0972b3d8e30bc88891bb1c2b0 broke this cop completely for me, so it now never complains!

**Comment by Darhazer** [comment]
Well, I guess you have to add the features spec folder to `Exclude` for the DescribeClass cop

**Comment by mvz** [comment]
@Darhazer Yes, that's what I did. An alternative for users who want the FeatureMethods cop enabled is to disable DescribeClass for the features spec folder.

**Comment by bquorning** [comment]
I am closing this issue, since the RSpec/Capybara/FeatureMethods cop was removed in #1876 / v3.0.0.
