### ISSUE TITLE
Cop idea: Restrict (defined?) block tags

### ISSUE THREAD

**Issue by choosen** [rubocop/rubocop-rspec#583]
I would like to restrict tags, which can be used in blocks: 
```
describe 'some test', type: feature, driver: :chrome, js: true, 
                      vcr: { record: :new_episodes } do
```
`feature 'admin can see sales inquiries', :js do`
`it 'makes us happy once per 2 runs', retry: 2`

* In my case I would to force using only tags: `:js, :vcr`.
* It can be useful to allow also some tag values, e.g. force to use only `driver: :chrome_headless`
* We can force to omit spec `:type` if we use `infer_spec_type_from_file_location`

Can we configure in cop settings which values are permitted?

**Comment by choosen** [comment]
@mapreal19  there is this one: https://rubydoc.info/gems/rubocop-rspec/2.17.1/RuboCop/Cop/RSpec/Rails/InferredSpecType

**Comment by choosen** [comment]
this can have similar implementation like : 
https://rubydoc.info/gems/rubocop-rspec/2.17.1/RuboCop/Cop/RSpec/SortMetadata

**Comment by pirj** [comment]
This could definitely make a useful custom cop.
The goal of this project is to enforce good common practices, including the ones from the community RSpec style guide.
Personally, I don't see if this can be qualified as a common practice. Thanks for understanding.

**Comment by choosen** [comment]
@pirj  custom cop is possible of course. I see your point.

I thought about community use case:

We have set
`config.filter_run_when_matching :focus`
Then we should not push focus meta tags to repo like we don't push code with `binding.pry`

**Comment by choosen** [comment]
thanks for pointing it out. Did not know about it
