### ISSUE TITLE
Capybara/FeatureMethods cop incorrectly specifies `feature` is just an alias of `describe`

### ISSUE THREAD

**Issue by twalpole** [rubocop/rubocop-rspec#650]
The `feature` method added by Capybara defines two pieces of metadata on the block - `type: features` and `capybara_feature: true` - it can't just be replaced  by `describe`

**Comment by pirj** [comment]
I guess the same applies to at least some [other replacements](https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/capybara/feature_methods.rb#L48), doesn't it?
What would you recommend, disable this cop by default?

**Comment by bquorning** [comment]
I am closing this issue, since the RSpec/Capybara/FeatureMethods cop was removed in #1876 / v3.0.0.
