### ISSUE TITLE
Prefer be_nil over be nil

### ISSUE THREAD

**Issue by nijikon** [rubocop/rubocop-rspec#693]
I would like to introduce a check like this.
``` ruby
# Bad
expect(foo).to be nil
# Good
expect(foo).to be_nil
```
My question is where should it be implemented. Should I add it in the [Predicate Matcher](https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/predicate_matcher.rb)?

**Comment by bquorning** [comment]
cc/ @Darhazer

**Comment by bquorning** [comment]
I think this is a duplicate of #176 and/or #244 – do you agree?

**Comment by nijikon** [comment]
I would say yes, I’m open to doing work on fixing those two as well. Just need your guidance where that work should be done. We could also solve the other issue that I saw which is some dead code in predicates matcher.

**Comment by nijikon** [comment]
Refs https://github.com/rubocop-hq/rubocop-rspec/issues/578

**Comment by nijikon** [comment]
Ping

**Comment by gardwired** [comment]
what about the fact that we have be true and be false.  seems more consistent to still be able to say be nil without the underscore no?  we no longer have be_true/false  so enforcing the now seemingly one-off be_nil feels odd to me.  my .0000btc.

**Comment by pirj** [comment]
>  we no longer have be_true/false

Can you please elaborate on that?

**Comment by bquorning** [comment]
In RSpec v3, the old `be_true` and `be_false` expectations were renamed to `be_truthy` and `be_falsey` to match with how they were actually implemented (e.g. `expect(nil).to be_false` was a passing spec in RSpec 2).

Maybe we can get _correctly implemented_ `be_true` and `be_false` back in RSpec 4?

**Comment by marcandre** [comment]
Can probably be closed now that #693 has been merged.

FWIW, I also find `be nil` to be preferable to `be_nil`
