### ISSUE TITLE
RSpec/ExpectActual false positive against routing specs (when using a negated matcher)

### ISSUE THREAD

**Issue by Drowze** [rubocop/rubocop-rspec#759]
On our project we have a test as follows:
```ruby
expect(get: :show, params: { id: 'null', format: :json }).not_to be_routable
```

Which is in turn raising a cop:
```ruby
C: RSpec/ExpectActual: Provide the actual you are testing to expect(...).
          expect(get: :show, params: { id: 'null', format: :json }).not_to be_routable
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I understand that this is very similar to #198. Our `route_to` tests work fine though.

Useful info:
```
$ bundle exec rubocop -v
0.64.0
$ bundle exec rails -v
Rails 5.2.3
$ ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]
```

**Comment by bquorning** [comment]
Hi @Drowze . What is the relative path to the file containing that test?

**Comment by Drowze** [comment]
```
integrations/live_games/spec/controllers/live_games/games_controller_spec.rb
```

LiveGames is a Rails engine under the integrations folder, hence the path.

**Comment by Darhazer** [comment]
@Drowze `ExpectActual` excludes specs in specs/routing by default, but your spec path doesn't match. You can add `integrations/live_games/spec/controllers/live_games/*_controller_spec.rb` to the exclude.

This is a workaround.

I guess the cop just should ignore cases when `be_routable` or `redirect_to` matchers are used
